"""Read-only AI explainer and logical language-model runtime helpers."""

from .federated_runtime import TrustedFederatedLanguageModelRuntime
from .ollama_provider import OllamaLanguageModelProvider, logical_provider_id
from .relay_remote import (
    RELAY_REMOTE_AI_KIND,
    BlockingRelayAIInvocationTransport,
    RelayRemoteAIEndpoint,
    RemoteAIProviderHost,
)
from .remote_contracts import (
    MAX_REMOTE_AI_CONTROL_MESSAGE_BYTES,
    MAX_REMOTE_AI_INVOCATION_TTL_SECONDS,
    REMOTE_AI_PROTOCOL,
    REMOTE_AI_PROTOCOL_MAJOR,
    REMOTE_AI_PROTOCOL_VERSION,
    REMOTE_AI_REQUEST_SCHEMA,
    REMOTE_AI_RESPONSE_SCHEMA,
    RemoteAIInvocationOutcome,
    RemoteAIInvocationRequest,
    RemoteAIInvocationResponse,
    validate_remote_ai_protocol,
)
from .remote_provider import (
    RemoteAIHealthAuthority,
    RemoteAIInvocationTransport,
    RemoteLanguageModelProvider,
    RemoteLanguageModelSnapshot,
    TrustedRemoteLanguageModelBinder,
)
from .runtime import (
    AIProviderInvocationError,
    AIRuntimePolicy,
    LANGUAGE_MODEL_CAPABILITY,
    LANGUAGE_MODEL_PROTOCOL,
    LANGUAGE_MODEL_PROTOCOL_VERSION,
    LanguageModelProvider,
    LanguageModelRuntime,
)
from .runtime_contracts import (
    AI_ATTEMPT_SCHEMA,
    AI_REQUEST_SCHEMA,
    AI_RESULT_SCHEMA,
    AI_RUNTIME_PROTOCOL,
    AI_RUNTIME_PROTOCOL_MAJOR,
    AI_RUNTIME_PROTOCOL_VERSION,
    AI_SELECTION_STATUS_SCHEMA,
    AIModality,
    AIProviderAttempt,
    AIProviderFailureClass,
    AIRuntimeError,
    AIRuntimeRequest,
    AIRuntimeResult,
    AISelectionStatus,
)
from .runtime_manager import ConfiguredLanguageModelRuntimeManager

__all__ = [
    "AI_ATTEMPT_SCHEMA",
    "AI_REQUEST_SCHEMA",
    "AI_RESULT_SCHEMA",
    "AI_RUNTIME_PROTOCOL",
    "AI_RUNTIME_PROTOCOL_MAJOR",
    "AI_RUNTIME_PROTOCOL_VERSION",
    "AI_SELECTION_STATUS_SCHEMA",
    "AIModality",
    "AIProviderAttempt",
    "AIProviderFailureClass",
    "AIProviderInvocationError",
    "AIRuntimeError",
    "AIRuntimePolicy",
    "AIRuntimeRequest",
    "AIRuntimeResult",
    "AISelectionStatus",
    "BlockingRelayAIInvocationTransport",
    "ConfiguredLanguageModelRuntimeManager",
    "LANGUAGE_MODEL_CAPABILITY",
    "LANGUAGE_MODEL_PROTOCOL",
    "LANGUAGE_MODEL_PROTOCOL_VERSION",
    "LanguageModelProvider",
    "LanguageModelRuntime",
    "MAX_REMOTE_AI_CONTROL_MESSAGE_BYTES",
    "MAX_REMOTE_AI_INVOCATION_TTL_SECONDS",
    "OllamaLanguageModelProvider",
    "RELAY_REMOTE_AI_KIND",
    "REMOTE_AI_PROTOCOL",
    "REMOTE_AI_PROTOCOL_MAJOR",
    "REMOTE_AI_PROTOCOL_VERSION",
    "REMOTE_AI_REQUEST_SCHEMA",
    "REMOTE_AI_RESPONSE_SCHEMA",
    "RelayRemoteAIEndpoint",
    "RemoteAIHealthAuthority",
    "RemoteAIInvocationOutcome",
    "RemoteAIInvocationRequest",
    "RemoteAIInvocationResponse",
    "RemoteAIInvocationTransport",
    "RemoteAIProviderHost",
    "RemoteLanguageModelProvider",
    "RemoteLanguageModelSnapshot",
    "TrustedFederatedLanguageModelRuntime",
    "TrustedRemoteLanguageModelBinder",
    "logical_provider_id",
    "validate_remote_ai_protocol",
]
