"""Command-driven setup helper for MSH.

Normal users can now start with one command and finish setup in the browser:

    docker compose up -d --build

This script remains for reproducible/server deployments where settings should be
provided by command instead of browser prompts.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import os
import secrets
import subprocess

from catalog.flask_app.services.server_setup_service import (
    AI_MODEL_CHOICES,
    AI_PROVIDER_MODES,
    DEFAULT_OLLAMA_BASE_URL,
    DEPLOYMENT_MODES,
    ServerSetupError,
    ServerSetupSettings,
    compose_profiles_for,
    env_lines_for,
    normalize_ollama_base_url,
    pull_ollama_model,
    save_settings,
)

ENV_PATH = Path(".env")

ONE_SHOT_MODES = {
    "prep-only": "prep",
    "observer-sync-only": "observer-sync",
}


def _prompt(text: str, default: str | None = None) -> str:
    suffix = f" [{default}]" if default is not None else ""
    value = input(f"{text}{suffix}: ").strip()
    return value if value else (default or "")


def _yes_no(text: str, default: bool = False) -> bool:
    default_text = "y" if default else "n"
    answer = _prompt(text, default_text).lower()
    return answer in {"y", "yes", "1", "true", "on"}


def _write_env(settings: ServerSetupSettings, *, web_bind: str, web_port: str, one_shot_profile: str | None = None) -> None:
    lines = [
        "# Local MSH setup generated by setup_msh.py",
        "# Browser setup stores runtime choices under data/server_setup/.",
        f"MSH_WEB_BIND={web_bind}",
        f"MSH_WEB_PORT={web_port}",
        f"MSH_FLASK_SECRET={secrets.token_urlsafe(32)}",
    ]
    if one_shot_profile:
        lines.extend(
            [
                f"MSH_DEPLOYMENT_MODE={settings.deployment_mode}",
                f"COMPOSE_PROFILES={one_shot_profile}",
                "MSH_SKIP_ORCHESTRATION=1",
                "MSH_SCAN_DIRS=results,data",
            ]
        )
    else:
        lines.extend(env_lines_for(settings))
    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _settings_from_args(args: argparse.Namespace) -> ServerSetupSettings:
    ai_profile = args.ai_profile or "laptop-standard"
    if ai_profile not in AI_MODEL_CHOICES:
        raise SystemExit(f"Unknown --ai-profile: {ai_profile}")
    if args.mode not in set(DEPLOYMENT_MODES) | set(ONE_SHOT_MODES):
        raise SystemExit(f"Unknown --mode: {args.mode}")
    ai_enabled = not args.no_ai and args.mode not in ONE_SHOT_MODES and args.mode != "recorder-only"
    provider_mode = args.ai_provider or "local"
    if provider_mode not in AI_PROVIDER_MODES:
        raise SystemExit(f"Unknown --ai-provider: {provider_mode}")
    if provider_mode == "connected":
        if not args.ollama_url:
            raise SystemExit("--ollama-url is required when --ai-provider=connected")
        try:
            ollama_base_url = normalize_ollama_base_url(args.ollama_url)
        except ServerSetupError as exc:
            raise SystemExit(str(exc)) from exc
        provider_name = (args.ai_provider_name or "Connected computer").strip()
    else:
        ollama_base_url = DEFAULT_OLLAMA_BASE_URL
        provider_name = "This computer"
    return ServerSetupSettings(
        configured=True,
        deployment_mode=args.mode,
        ai_enabled=ai_enabled,
        ai_provider_mode=provider_mode,
        ai_provider_name=provider_name,
        ai_profile=ai_profile,
        ai_model=AI_MODEL_CHOICES[ai_profile]["model"],
        ollama_base_url=ollama_base_url,
        recorder_sources=args.recorder_sources or "",
        recorder_poll_interval=str(args.recorder_poll_interval),
        recorder_include_condition=bool(args.recorder_include_condition),
        updated_at="command",
    )


def _interactive_settings() -> tuple[ServerSetupSettings, str, str, bool, bool]:
    print("MSH setup")
    print("For browser setup, use only: docker compose up -d --build")
    print("For command-driven setup, answer the questions below.\n")
    modes = list(DEPLOYMENT_MODES) + list(ONE_SHOT_MODES)
    for index, mode in enumerate(modes, start=1):
        description = DEPLOYMENT_MODES.get(mode, {}).get("description") or f"Run {ONE_SHOT_MODES[mode]} one-shot service."
        print(f"{index}. {mode}: {description}")
    selected = _prompt("Choose mode", "1")
    try:
        mode = modes[int(selected) - 1]
    except (ValueError, IndexError):
        raise SystemExit(f"Unknown mode selection: {selected}")

    web_bind = _prompt("Web bind address", "0.0.0.0")
    web_port = _prompt("Web port", "5000")
    no_ai = False
    ai_profile = "laptop-standard"
    ai_provider = "local"
    ai_provider_name = "This computer"
    ollama_url = ""
    if mode not in ONE_SHOT_MODES and mode != "recorder-only":
        no_ai = not _yes_no("Enable AI explainer", True)
        if not no_ai:
            ai_provider = _prompt("Language-model provider (local or connected)", "local")
            if ai_provider == "connected":
                ai_provider_name = _prompt("Connected computer name", "Laptop")
                ollama_url = _prompt("Connected Ollama URL", "http://192.168.1.50:11434")
            print("\nAI model choices")
            for key, choice in AI_MODEL_CHOICES.items():
                print(f"- {key}: {choice['model']} ({choice['device']})")
            ai_profile = _prompt("AI profile", "laptop-standard")
    recorder_sources = ""
    poll_interval = "0.2"
    include_condition = False
    if mode in {"full-server", "recorder-only"}:
        recorder_sources = _prompt("Recorder sources", "")
        poll_interval = _prompt("Recorder poll interval seconds", "0.2")
        include_condition = _yes_no("Record MTConnect condition values", False)

    args = argparse.Namespace(
        mode=mode,
        ai_profile=ai_profile,
        no_ai=no_ai,
        ai_provider=ai_provider,
        ai_provider_name=ai_provider_name,
        ollama_url=ollama_url,
        recorder_sources=recorder_sources,
        recorder_poll_interval=poll_interval,
        recorder_include_condition=include_condition,
    )
    settings = _settings_from_args(args)
    pull_model = settings.ai_enabled and _yes_no("Pull selected Ollama model now", True)
    start = _yes_no("Start Docker Compose now", True)
    return settings, web_bind, web_port, pull_model, start


def _run_compose(settings: ServerSetupSettings, *, pull_model: bool, start: bool, one_shot_profile: str | None = None) -> None:
    env = os.environ.copy()
    env["COMPOSE_PROFILES"] = one_shot_profile or compose_profiles_for(settings)
    if start:
        subprocess.run(["docker", "compose", "up", "-d", "--build"], env=env, check=False)
    if pull_model and settings.ai_enabled:
        if settings.ai_provider_mode == "connected":
            ok, message = pull_ollama_model(settings)
            print(message)
            if not ok:
                print("The connected model was not installed; setup can still be saved and retried in the browser.")
        else:
            subprocess.run(["docker", "compose", "up", "-d", "ollama"], env=env, check=False)
            subprocess.run(["docker", "compose", "run", "--rm", "ollama-pull"], env=env, check=False)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Configure MSH from the command line.")
    parser.add_argument("--mode", choices=sorted(set(DEPLOYMENT_MODES) | set(ONE_SHOT_MODES)), help="Deployment mode to write without prompts.")
    parser.add_argument("--ai-profile", choices=sorted(AI_MODEL_CHOICES), default="laptop-standard", help="Standard Ollama model choice.")
    parser.add_argument("--ai-provider", choices=sorted(AI_PROVIDER_MODES), default="local", help="Run Ollama locally or use a connected computer.")
    parser.add_argument("--ai-provider-name", default="", help="Friendly name for a connected AI provider, such as Laptop.")
    parser.add_argument("--ollama-url", default="", help="Ollama root URL when --ai-provider=connected.")
    parser.add_argument("--no-ai", action="store_true", help="Disable the AI explainer in generated settings.")
    parser.add_argument("--recorder-sources", default="", help="MTConnect recorder sources, e.g. IG500=http://.../current;VTC=http://.../current")
    parser.add_argument("--recorder-poll-interval", default="0.2", help="Recorder poll interval in seconds.")
    parser.add_argument("--recorder-include-condition", action="store_true", help="Record MTConnect condition values.")
    parser.add_argument("--web-bind", default="0.0.0.0", help="Web bind address for Docker Compose.")
    parser.add_argument("--web-port", default="5000", help="Published web port.")
    parser.add_argument("--pull-model", action="store_true", help="Pull the selected Ollama model using Docker Compose.")
    parser.add_argument("--start", action="store_true", help="Start Docker Compose after writing settings.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.mode:
        settings = _settings_from_args(args)
        web_bind = args.web_bind
        web_port = args.web_port
        pull_model = args.pull_model
        start = args.start
    else:
        settings, web_bind, web_port, pull_model, start = _interactive_settings()

    one_shot_profile = ONE_SHOT_MODES.get(settings.deployment_mode)
    Path("data").mkdir(exist_ok=True)
    Path("results").mkdir(exist_ok=True)
    if not one_shot_profile:
        save_settings(settings)
    _write_env(settings, web_bind=web_bind, web_port=web_port, one_shot_profile=one_shot_profile)
    print(f"Wrote {ENV_PATH}")
    if not one_shot_profile:
        print("Wrote data/server_setup/server_settings.json")
    print("Browser-first startup command:")
    print("  docker compose up -d --build")
    print("Command-driven start command:")
    print("  python setup_msh.py --mode web-workbench --ai-profile laptop-standard --start")
    _run_compose(settings, pull_model=pull_model, start=start, one_shot_profile=one_shot_profile)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
