"""Command-driven setup helper for FCP.

Normal product setup remains capability-first in the browser. This script is for
reproducible local process composition and technical configuration. Command
profiles never grant contribution authority or mark capability onboarding done.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import secrets
import subprocess

from catalog.command_setup import (
    COMMAND_PROFILES,
    CommandDeploymentPlan,
    accepted_profile_names,
    build_command_plan,
    env_lines_for_plan,
    pull_connected_model,
)
from catalog.flask_app.services.capability_config_service import (
    AI_MODEL_CHOICES,
    AI_PROVIDER_MODES,
    CAPABILITY_CONFIG_PATH,
    CapabilityConfigError,
    save_capability_config,
)

ENV_PATH = Path(".env")


def _prompt(text: str, default: str | None = None) -> str:
    suffix = f" [{default}]" if default is not None else ""
    value = input(f"{text}{suffix}: ").strip()
    return value if value else (default or "")


def _yes_no(text: str, default: bool = False) -> bool:
    default_text = "y" if default else "n"
    answer = _prompt(text, default_text).lower()
    return answer in {"y", "yes", "1", "true", "on"}


def _write_env(
    plan: CommandDeploymentPlan,
    *,
    web_bind: str,
    web_port: str,
) -> None:
    lines = [
        "# Local FCP process configuration generated by setup_fcp.py",
        "# Capability authority is stored by capability-first onboarding, not here.",
        f"FCP_WEB_BIND={web_bind}",
        f"FCP_WEB_PORT={web_port}",
        f"FCP_FLASK_SECRET={secrets.token_urlsafe(32)}",
        *env_lines_for_plan(plan),
    ]
    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _plan_from_args(args: argparse.Namespace) -> CommandDeploymentPlan:
    try:
        return build_command_plan(
            profile=getattr(args, "profile", None),
            ai_profile=getattr(args, "ai_profile", None),
            no_ai=bool(getattr(args, "no_ai", False)),
            ai_provider=getattr(args, "ai_provider", "local"),
            ai_provider_name=str(getattr(args, "ai_provider_name", "") or ""),
            ollama_url=str(getattr(args, "ollama_url", "") or ""),
            recorder_sources=str(getattr(args, "recorder_sources", "") or ""),
            recorder_poll_interval=str(
                getattr(args, "recorder_poll_interval", "0.2") or "0.2"
            ),
            recorder_include_condition=bool(
                getattr(args, "recorder_include_condition", False)
            ),
        )
    except CapabilityConfigError as exc:
        raise SystemExit(str(exc)) from exc


def _interactive_plan() -> tuple[CommandDeploymentPlan, str, str, bool, bool]:
    print("FCP command setup")
    print("Capability choices are completed in /onboarding.")
    print("This helper configures local processes and technical parameters only.\n")

    profiles = list(COMMAND_PROFILES)
    for index, profile in enumerate(profiles, start=1):
        definition = COMMAND_PROFILES[profile]
        print(f"{index}. {profile}: {definition['description']}")
    selected = _prompt("Choose command profile", "1")
    try:
        profile = profiles[int(selected) - 1]
    except (ValueError, IndexError):
        raise SystemExit(f"Unknown profile selection: {selected}")

    web_bind = "0.0.0.0"
    web_port = "5000"
    if profile in {"workbench", "web-only", "recorder"}:
        web_bind = _prompt("Web bind address", web_bind)
        web_port = _prompt("Web port", web_port)

    no_ai = False
    ai_profile = "laptop-standard"
    ai_provider = "local"
    ai_provider_name = "This computer"
    ollama_url = ""
    if profile == "language-model-provider":
        print("\nAI model choices")
        for key, choice in AI_MODEL_CHOICES.items():
            print(f"- {key}: {choice['model']} ({choice['device']})")
        ai_profile = _prompt("AI profile", "edge-small")
    elif profile not in {"prep", "observer-sync", "recorder"}:
        no_ai = not _yes_no("Provision a local AI model now", True)
        if not no_ai:
            ai_provider = _prompt(
                "Language-model provider (local or connected)",
                "local",
            )
            if ai_provider == "connected":
                ai_provider_name = _prompt("Connected computer name", "Laptop")
                ollama_url = _prompt(
                    "Connected Ollama URL",
                    "http://192.168.1.50:11434",
                )
            print("\nAI model choices")
            for key, choice in AI_MODEL_CHOICES.items():
                print(f"- {key}: {choice['model']} ({choice['device']})")
            ai_profile = _prompt("AI profile", "laptop-standard")

    recorder_sources = ""
    poll_interval = "0.2"
    include_condition = False
    if profile == "recorder":
        recorder_sources = _prompt("Recorder sources", "")
        poll_interval = _prompt("Recorder poll interval seconds", "0.2")
        include_condition = _yes_no("Record MTConnect condition values", False)

    args = argparse.Namespace(
        profile=profile,
        ai_profile=ai_profile,
        no_ai=no_ai,
        ai_provider=ai_provider,
        ai_provider_name=ai_provider_name,
        ollama_url=ollama_url,
        recorder_sources=recorder_sources,
        recorder_poll_interval=poll_interval,
        recorder_include_condition=include_condition,
    )
    plan = _plan_from_args(args)
    pull_model = (
        plan.provider_node
        or plan.config.ai_provider_mode == "connected"
        or plan.provision_local_model
    ) and _yes_no("Pull selected Ollama model now", True)
    start = _yes_no("Run the selected Docker Compose command now", True)
    return plan, web_bind, web_port, pull_model, start


def _run_compose(
    plan: CommandDeploymentPlan,
    *,
    pull_model: bool,
    start: bool,
) -> None:
    env = os.environ.copy()
    env["COMPOSE_PROFILES"] = plan.compose_profile

    if plan.provider_node:
        env["FCP_PROVIDER_MODEL"] = plan.config.ai_model
        if start:
            subprocess.run(
                [
                    "docker",
                    "compose",
                    "--profile",
                    "provider",
                    "up",
                    "-d",
                    "model-provider",
                ],
                env=env,
                check=True,
            )
        if pull_model:
            subprocess.run(
                [
                    "docker",
                    "compose",
                    "--profile",
                    "provider",
                    "run",
                    "--rm",
                    "model-provider-install",
                ],
                env=env,
                check=True,
            )
        return

    if plan.one_shot_service:
        if start:
            subprocess.run(
                [
                    "docker",
                    "compose",
                    "--profile",
                    plan.compose_profile,
                    "run",
                    "--rm",
                    plan.one_shot_service,
                ],
                env=env,
                check=True,
            )
        return

    if start:
        command = ["docker", "compose", "up", "-d", "--build"]
        if plan.profile == "web-only":
            command.extend(["flask", "relay"])
        elif plan.profile == "recorder":
            command.extend(["flask", "recorder", "relay"])
        subprocess.run(command, env=env, check=False)

    if not pull_model:
        return
    if plan.config.ai_provider_mode == "connected":
        ok, message = pull_connected_model(plan.config)
        print(message)
        if not ok:
            print(
                "The connected model was not installed; technical configuration "
                "was still saved and can be retried later."
            )
        return
    if not plan.provision_local_model:
        print(
            "Local model provisioning was suppressed. Capability onboarding "
            "still decides whether language-model contribution is enabled."
        )
        return
    subprocess.run(
        ["docker", "compose", "up", "-d", "ollama"],
        env=env,
        check=False,
    )
    subprocess.run(
        ["docker", "compose", "run", "--rm", "ollama-pull"],
        env=env,
        check=False,
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Configure FCP process composition and technical parameters."
    )
    parser.add_argument(
        "--profile",
        "--mode",
        dest="profile",
        choices=accepted_profile_names(),
        help=(
            "Local command profile. --mode is retained as a compatibility alias; "
            "neither spelling creates a device role."
        ),
    )
    parser.add_argument(
        "--ai-profile",
        choices=sorted(AI_MODEL_CHOICES),
        default=None,
        help="Standard Ollama model choice. Provider nodes default to edge-small.",
    )
    parser.add_argument(
        "--ai-provider",
        choices=sorted(AI_PROVIDER_MODES),
        default="local",
        help="Use local Ollama technical configuration or a connected computer.",
    )
    parser.add_argument(
        "--ai-provider-name",
        default="",
        help="Friendly name for a connected AI provider, such as Laptop.",
    )
    parser.add_argument(
        "--ollama-url",
        default="",
        help="Ollama root URL when --ai-provider=connected.",
    )
    parser.add_argument(
        "--no-ai",
        action="store_true",
        help=(
            "Do not provision a local model. This does not disable or enable "
            "language-model contribution authority."
        ),
    )
    parser.add_argument(
        "--recorder-sources",
        default="",
        help="MTConnect recorder sources, e.g. IG500=http://.../current.",
    )
    parser.add_argument(
        "--recorder-poll-interval",
        default="0.2",
        help="Recorder poll interval in seconds.",
    )
    parser.add_argument(
        "--recorder-include-condition",
        action="store_true",
        help="Record MTConnect condition values when recorder authority is enabled.",
    )
    parser.add_argument(
        "--web-bind",
        default="0.0.0.0",
        help="Web bind address for Docker Compose.",
    )
    parser.add_argument(
        "--web-port",
        default="5000",
        help="Published web port.",
    )
    parser.add_argument(
        "--pull-model",
        action="store_true",
        help="Pull the selected Ollama model using the configured provider.",
    )
    parser.add_argument(
        "--start",
        action="store_true",
        help="Run the selected Docker Compose command after writing configuration.",
    )
    parser.add_argument(
        "--browser-setup-pending",
        action="store_true",
        help=argparse.SUPPRESS,
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.profile:
        plan = _plan_from_args(args)
        web_bind = args.web_bind
        web_port = args.web_port
        pull_model = args.pull_model
        start = args.start
    else:
        plan, web_bind, web_port, pull_model, start = _interactive_plan()

    if args.browser_setup_pending:
        print(
            "--browser-setup-pending is no longer needed: command setup never "
            "marks capability onboarding complete."
        )

    Path("data").mkdir(exist_ok=True)
    Path("results").mkdir(exist_ok=True)
    if plan.one_shot_service is None:
        save_capability_config(plan.config)
        print(f"Wrote {CAPABILITY_CONFIG_PATH}")
    _write_env(plan, web_bind=web_bind, web_port=web_port)
    print(f"Wrote {ENV_PATH}")

    if plan.provider_node:
        print("Language-model provider command:")
        print(
            "  python setup_fcp.py --profile language-model-provider "
            "--ai-profile edge-small --start --pull-model"
        )
        print("Connect another FCP device to http://<this-laptop-ip>:11434")
    elif plan.one_shot_service:
        print(f"One-shot profile selected: {plan.profile}")
    else:
        print(
            "Technical configuration is ready. Capability contribution authority "
            "is still selected through /onboarding."
        )
        print("Start command:")
        print("  python setup_fcp.py --profile workbench --start")

    _run_compose(plan, pull_model=pull_model, start=start)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
