"""Interactive setup helper for selecting which MSH server components run.

The helper writes a local `.env` file used by Docker Compose. The file is ignored
by git and can be rerun whenever this checkout should behave as another server
role: full server, web workbench, recorder-only, or one-shot preparation/sync.
"""

from __future__ import annotations

from pathlib import Path
import secrets


ENV_PATH = Path(".env")

MODES = {
    "1": {
        "name": "full-server",
        "description": "Flask workbench + MTConnect recorder",
        "profiles": "full",
        "skip_orchestration": "0",
    },
    "2": {
        "name": "web-workbench",
        "description": "Flask workbench with background orchestration",
        "profiles": "web",
        "skip_orchestration": "0",
    },
    "3": {
        "name": "web-ui-only",
        "description": "Flask UI only; no background orchestration",
        "profiles": "web",
        "skip_orchestration": "1",
    },
    "4": {
        "name": "recorder-only",
        "description": "MTConnect data recorder only; no Flask web UI",
        "profiles": "recorder",
        "skip_orchestration": "1",
    },
    "5": {
        "name": "prep-only",
        "description": "One-shot preparation/orchestration container",
        "profiles": "prep",
        "skip_orchestration": "1",
    },
    "6": {
        "name": "observer-sync-only",
        "description": "One-shot Observer Phoenix sync container",
        "profiles": "observer-sync",
        "skip_orchestration": "1",
    },
}


def _prompt(text: str, default: str | None = None) -> str:
    suffix = f" [{default}]" if default is not None else ""
    value = input(f"{text}{suffix}: ").strip()
    return value if value else (default or "")


def _yes_no(text: str, default: bool = False) -> bool:
    default_text = "y" if default else "n"
    answer = _prompt(text, default_text).lower()
    return answer in {"y", "yes", "1", "true"}


def _recorder_sources_prompt() -> str:
    print("\nMTConnect recorder sources")
    print("Leave empty to use the built-in lab defaults, or enter entries like:")
    print("  IG500=http://192.168.200.251:5000/current;VTC=http://192.168.200.252:5000/current")
    return _prompt("Recorder sources", "")


def _render_env(values: dict[str, str]) -> str:
    lines = [
        "# Local MSH server setup generated by setup_msh.py",
        "# This file is intentionally ignored by git.",
    ]
    for key, value in values.items():
        escaped = value.replace("\\", "\\\\").replace("\n", "")
        lines.append(f"{key}={escaped}")
    return "\n".join(lines) + "\n"


def main() -> int:
    print("MSH server setup")
    print("Select which parts of this checkout should run with Docker Compose.\n")
    for key, mode in MODES.items():
        print(f"{key}. {mode['name']}: {mode['description']}")

    selected = _prompt("Choose mode", "1")
    if selected not in MODES:
        print(f"Unknown mode: {selected}")
        return 2
    mode = MODES[selected]

    env: dict[str, str] = {
        "MSH_DEPLOYMENT_MODE": mode["name"],
        "COMPOSE_PROFILES": mode["profiles"],
        "MSH_SKIP_ORCHESTRATION": mode["skip_orchestration"],
        "MSH_SCAN_DIRS": "results,data",
        "MSH_WEB_BIND": _prompt("Web bind address", "0.0.0.0"),
        "MSH_WEB_PORT": _prompt("Web port", "5000"),
        "MSH_FLASK_SECRET": secrets.token_urlsafe(32),
    }

    if mode["profiles"] in {"full", "recorder"}:
        recorder_sources = _recorder_sources_prompt()
        if recorder_sources:
            env["MSH_RECORDER_SOURCES"] = recorder_sources
        env["MSH_RECORDER_DATA_DIR"] = "data"
        env["MSH_RECORDER_STATE_FILE"] = "data/source_state/mtconnect_recorder_state.json"
        env["MSH_RECORDER_POLL_INTERVAL"] = _prompt("Recorder poll interval seconds", "0.2")
        env["MSH_RECORDER_FLUSH_INTERVAL"] = _prompt("Recorder flush interval seconds", "1.0")
        env["MSH_RECORDER_REQUEST_TIMEOUT"] = _prompt("Recorder request timeout seconds", "1.0")
        env["MSH_RECORDER_INCLUDE_CONDITION"] = "true" if _yes_no("Record MTConnect condition values", False) else "false"

    ENV_PATH.write_text(_render_env(env), encoding="utf-8")
    Path("data").mkdir(exist_ok=True)
    Path("results").mkdir(exist_ok=True)

    print(f"\nWrote {ENV_PATH}")
    print("Start the selected server components with:")
    print("  docker compose up -d --build")
    print("View logs with:")
    print("  docker compose logs -f")
    if "web" in mode["profiles"] or mode["profiles"] == "full":
        print(f"Open: http://<server-ip>:{env['MSH_WEB_PORT']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
