"""Start the FCP MTConnect recorder, optionally as a headless Federation node.

The simplest first-run form is now::

    python start_recorder.py FCP1-...

The recorder creates/reuses its stable identity, joins the Federation, runs the
existing bounded private-network MTConnect scan, selects discovered sources on
first configuration, starts managed recording, and accepts later scan/source
changes from any trusted Federation member. Manual ``NAME=URL`` sources remain
available for explicit deployments.
"""

from __future__ import annotations

import json
import math
import os
import runpy
import sys
from argparse import ArgumentParser, Namespace
from collections.abc import Mapping
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit

from catalog.federation.errors import (
    AuthenticationError,
    FederationOperationError,
    FederationValidationError,
)
from catalog.flask_app.services.capability_config_service import (
    CapabilityConfig,
    CapabilityConfigError,
    format_recorder_sources,
    load_capability_config,
    parse_recorder_sources,
    save_capability_config,
    update_recorder_config,
)
from catalog.flask_app.services.mtconnect_discovery_service import (
    DEFAULT_MTCONNECT_PORT,
    MtconnectDiscoveryError,
    MtconnectDiscoveryService,
    validate_scan_cidr,
)
from catalog.mtconnect_recorder.federation_control import (
    RecorderFederationControlWorker,
    infer_private_scan_cidr,
)
from catalog.mtconnect_recorder.federation_node import (
    MAX_FEDERATION_REQUEST_SECONDS,
    MAX_SHARING_READY_SECONDS,
    RecorderFederationNode,
)
from catalog.mtconnect_recorder.upgrade_compat import ensure_recorder_upgrade_config

_AUTO_CONFIG_SCHEMA = "fcp.mtconnect_recorder.autoconfig.v1"
_CONTROL_SCHEMA = "fcp.mtconnect_recorder.control.v1"


def _source(value: str) -> tuple[str, str]:
    if "=" not in value:
        raise ValueError(
            "Use NAME=http://host:port, for example "
            "Mazak=http://192.168.10.20:5000"
        )
    name, url = value.split("=", 1)
    name = name.strip()
    url = url.strip()
    parsed = urlsplit(url)
    if not name or parsed.scheme not in {"http", "https"} or not parsed.netloc:
        raise ValueError(f"Invalid MTConnect source: {value!r}")
    return name, url


def _read_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return value if isinstance(value, dict) else {}


def _write_json_atomic(path: Path, value: Mapping[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    temporary = path.with_name(path.name + ".tmp")
    temporary.write_text(
        json.dumps(dict(value), sort_keys=True, separators=(",", ":")) + "\n",
        encoding="utf-8",
    )
    os.replace(temporary, path)
    try:
        path.chmod(0o600)
    except OSError:
        pass


def build_parser() -> ArgumentParser:
    parser = ArgumentParser(
        description="Start the loss-aware FCP MTConnect recorder.",
        allow_abbrev=False,
    )
    parser.add_argument(
        "inputs",
        nargs="*",
        metavar="FCP1-...|NAME=URL",
        help=(
            "Usually only the first-use FCP1 pairing key. Optional manual "
            "MTConnect sources may still be supplied as NAME=URL."
        ),
    )
    parser.add_argument(
        "--data-dir",
        default="data",
        help="Output directory (default: data).",
    )
    parser.add_argument(
        "--poll-interval",
        type=float,
        default=0.2,
        help="Seconds between catch-up cycles (default: 0.2).",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=1000,
        help="Maximum observations requested per /sample call (default: 1000).",
    )
    parser.add_argument(
        "--max-batches-per-cycle",
        type=int,
        default=20,
        help="Maximum catch-up batches per source and cycle (default: 20).",
    )
    parser.add_argument(
        "--timeout",
        type=float,
        default=10.0,
        help="HTTP timeout in seconds (default: 10).",
    )
    parser.add_argument(
        "--once",
        action="store_true",
        help="Run one catch-up cycle and exit.",
    )
    parser.add_argument(
        "--federation-key",
        help=(
            "Signed FCP1 pairing key generated by the Federation. It may also "
            "be supplied as the only positional argument. Required only for "
            "the first join and never persisted."
        ),
    )
    parser.add_argument(
        "--device-name",
        default="FCP MTConnect recorder",
        help="Stable display name used for this recorder identity.",
    )
    parser.add_argument(
        "--storage-group",
        help=(
            "Logical Federation storage group for recorder data. If omitted, "
            "the recorder auto-selects when exactly one ready group exists."
        ),
    )
    parser.add_argument(
        "--federation-timeout",
        type=float,
        default=15.0,
        help="Federation request timeout in seconds (default: 15).",
    )
    parser.add_argument(
        "--require-federation",
        action="store_true",
        help=(
            "Exit instead of recording locally when initial Federation "
            "join/reconnect fails."
        ),
    )
    parser.add_argument(
        "--require-data-sharing",
        action="store_true",
        help=(
            "Require the authenticated recorder publication path to reach a "
            "ready logical-storage group before capture starts."
        ),
    )
    parser.add_argument(
        "--sharing-timeout",
        type=float,
        default=45.0,
        help=(
            "Seconds to wait for required Federation data sharing "
            "(default: 45)."
        ),
    )
    parser.add_argument(
        "--scan-cidr",
        default="",
        help=(
            "Optional private IPv4 CIDR for startup discovery. If omitted, "
            "the recorder infers a bounded /24 from its own network."
        ),
    )
    parser.add_argument(
        "--scan-port",
        type=int,
        default=DEFAULT_MTCONNECT_PORT,
        help=f"MTConnect port used by startup discovery (default: {DEFAULT_MTCONNECT_PORT}).",
    )
    parser.add_argument(
        "--no-auto-scan",
        action="store_true",
        help="Skip the default startup MTConnect network scan.",
    )
    return parser


def _classify_inputs(
    parser: ArgumentParser,
    args: Namespace,
) -> tuple[str | None, list[tuple[str, str]]]:
    pairing_key = str(args.federation_key or "").strip() or None
    environment_key = os.environ.pop("FCP_RECORDER_FEDERATION_KEY", None)
    if environment_key:
        environment_key = environment_key.strip()
        if pairing_key and environment_key != pairing_key:
            parser.error("Conflicting Federation pairing keys were supplied.")
        pairing_key = environment_key

    sources: list[tuple[str, str]] = []
    for value in args.inputs:
        normalized = str(value).strip()
        if normalized.startswith("FCP1-") and "=" not in normalized:
            if pairing_key and pairing_key != normalized:
                parser.error("Only one Federation pairing key may be supplied.")
            pairing_key = normalized
            continue
        try:
            sources.append(_source(normalized))
        except ValueError as exc:
            parser.error(str(exc))
    return pairing_key, sources


def _selection_complete(path: Path, configured_sources: dict[str, str]) -> bool:
    marker = _read_json(path)
    if (
        marker.get("schema") == _AUTO_CONFIG_SCHEMA
        and marker.get("initial_selection_complete") is True
    ):
        return True
    # Existing explicit configuration predates this marker and must not be
    # expanded automatically on every later restart.
    return bool(configured_sources)


def _mark_selection_complete(path: Path, *, requested_by: str) -> None:
    _write_json_atomic(
        path,
        {
            "schema": _AUTO_CONFIG_SCHEMA,
            "initial_selection_complete": True,
            "requested_by": requested_by,
        },
    )


def _prepare_recorder_configuration(
    *,
    parser: ArgumentParser,
    args: Namespace,
    data_dir: Path,
    manual_sources: list[tuple[str, str]],
) -> tuple[CapabilityConfig, list[tuple[str, str]]]:
    config_path = data_dir / "capabilities" / "config.json"
    state_dir = data_dir / "source_state"
    control_path = state_dir / "mtconnect_recorder_control.json"
    marker_path = state_dir / "mtconnect_recorder_autoconfig.json"
    discovery = MtconnectDiscoveryService(
        scan_path=state_dir / "mtconnect_network_scan.json",
        config_path=config_path,
        checkpoint_path=state_dir / "mtconnect_recorder_state.json",
    )

    try:
        config = load_capability_config(config_path)
        configured = parse_recorder_sources(config.recorder_sources)
    except CapabilityConfigError as exc:
        parser.error(str(exc))

    selection_complete = _selection_complete(marker_path, configured)
    if manual_sources:
        configured = dict(manual_sources)
        config = update_recorder_config(
            config,
            recorder_sources=format_recorder_sources(configured),
            recorder_poll_interval=str(args.poll_interval),
        )
        selection_complete = True
        _mark_selection_complete(marker_path, requested_by="manual-startup-sources")

    if not args.no_auto_scan:
        cidr = str(args.scan_cidr or "").strip()
        try:
            if cidr:
                cidr = str(validate_scan_cidr(cidr))
            else:
                cidr = discovery.recommended_cidr(config) or infer_private_scan_cidr()
                if cidr:
                    cidr = str(validate_scan_cidr(cidr))
        except MtconnectDiscoveryError as exc:
            parser.error(str(exc))

        if cidr:
            print(f"Scanning recorder network {cidr} on MTConnect port {args.scan_port}...")
            try:
                scan = discovery.scan(cidr, port=args.scan_port)
            except MtconnectDiscoveryError as exc:
                print(f"Startup network scan unavailable: {exc}", file=sys.stderr)
            else:
                print(
                    "Startup network scan found "
                    f"{scan.get('machines_found', 0)} machine(s) from "
                    f"{scan.get('agents_found', 0)} MTConnect Agent(s)."
                )
                if not selection_complete and not configured:
                    source_ids = [
                        str(item.get("source_id") or "")
                        for item in scan.get("results", [])
                        if isinstance(item, dict) and item.get("source_id")
                    ]
                    if source_ids:
                        config = discovery.merge_selected_results(config, source_ids)
                        configured = parse_recorder_sources(config.recorder_sources)
                        selection_complete = True
                        _mark_selection_complete(
                            marker_path,
                            requested_by="first-start-auto-scan",
                        )
                        print(
                            f"First startup selected {len(configured)} discovered "
                            "MTConnect source(s)."
                        )
        else:
            print(
                "Startup network scan skipped because no private IPv4 /24 could "
                "be inferred. After Federation pairing, start a scan from any "
                "Federation device or pass --scan-cidr.",
                file=sys.stderr,
            )

    # Preserve an intentionally empty source selection after it has been
    # managed remotely. Only first configuration auto-selects all scan results.
    config = update_recorder_config(
        config,
        recorder_sources=format_recorder_sources(configured),
        recorder_poll_interval=str(args.poll_interval),
    )
    save_capability_config(config, config_path)
    configured = parse_recorder_sources(config.recorder_sources)

    _write_json_atomic(
        control_path,
        {
            "schema": _CONTROL_SCHEMA,
            "enabled": bool(configured),
            "requested_by": "start-recorder",
        },
    )
    return config, list(configured.items())


def _start_federation(
    *,
    args: Namespace,
    pairing_key: str | None,
    data_dir: Path,
    parsed_sources: list[tuple[str, str]],
) -> RecorderFederationNode | None:
    node = RecorderFederationNode(
        data_directory=data_dir,
        display_name=args.device_name,
        source_names=tuple(name for name, _url in parsed_sources),
        requested_storage_group=args.storage_group,
        request_timeout=args.federation_timeout,
    )
    keep_node = False
    try:
        try:
            if pairing_key is None and not node.has_saved_membership():
                if args.require_federation or args.require_data_sharing:
                    raise FederationOperationError(
                        "recorder-pairing-required",
                        "required Federation startup needs a saved membership or a "
                        "fresh FCP1 pairing code",
                        "pairing_key",
                    )
                print("Federation: local-only (pass an FCP1-... key to join).")
                return None
            snapshot = node.bootstrap(pairing_key)
        except (
            AuthenticationError,
            FederationOperationError,
            FederationValidationError,
            OSError,
            RuntimeError,
            TimeoutError,
        ) as exc:
            code = str(getattr(exc, "code", type(exc).__name__))
            message = str(getattr(exc, "message", str(exc) or type(exc).__name__))
            print(
                f"Federation bootstrap unavailable ({code}): {message}",
                file=sys.stderr,
            )
            if args.require_federation or args.require_data_sharing:
                raise
            print(
                "Recording will continue locally. No pairing key or Federation "
                "credential was persisted by the failed attempt.",
                file=sys.stderr,
            )
            return None

        if args.require_data_sharing:
            try:
                snapshot = node.wait_until_sharing_ready(
                    timeout_seconds=args.sharing_timeout,
                )
            except Exception as exc:
                code = str(getattr(exc, "code", type(exc).__name__))
                message = str(
                    getattr(exc, "message", str(exc) or type(exc).__name__)
                )
                print(
                    f"Federation data sharing unavailable ({code}): {message}",
                    file=sys.stderr,
                )
                raise

        print("Federation: connected")
        print(f"  Device:     {snapshot.node_id}")
        print(f"  Federation: {snapshot.federation_id}")
        print(f"  Session:    {snapshot.session_id}")
        if snapshot.storage_group:
            print(f"  Data group: {snapshot.storage_group}")
        elif args.storage_group:
            print(f"  Data group: {args.storage_group} (waiting for authority)")
        else:
            print("  Data group: auto-select one ready logical-storage group")
        jsonl_state = getattr(snapshot, "jsonl_state", None)
        if isinstance(jsonl_state, str) and jsonl_state:
            print(f"  JSONL:      supported local data/**/*.jsonl ({jsonl_state})")
        print(
            "  Delivery:   recorder observations plus supported JSONL; durable "
            "backlogs retry independently"
        )
        keep_node = True
        return node
    finally:
        if not keep_node:
            try:
                node.stop()
            except Exception:  # noqa: BLE001, S110 - preserve startup failure
                pass


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    pairing_key, manual_sources = _classify_inputs(parser, args)

    if args.poll_interval <= 0:
        parser.error("--poll-interval must be greater than zero.")
    if args.batch_size <= 0:
        parser.error("--batch-size must be greater than zero.")
    if args.max_batches_per_cycle <= 0:
        parser.error("--max-batches-per-cycle must be greater than zero.")
    if args.timeout <= 0:
        parser.error("--timeout must be greater than zero.")
    if (
        not math.isfinite(args.federation_timeout)
        or not 0 < args.federation_timeout <= MAX_FEDERATION_REQUEST_SECONDS
    ):
        parser.error(
            "--federation-timeout must be finite, greater than zero, and at most "
            f"{MAX_FEDERATION_REQUEST_SECONDS:g} seconds."
        )
    if (
        not math.isfinite(args.sharing_timeout)
        or not 0 < args.sharing_timeout <= MAX_SHARING_READY_SECONDS
    ):
        parser.error(
            "--sharing-timeout must be finite, greater than zero, and at most "
            f"{MAX_SHARING_READY_SECONDS:g} seconds."
        )
    if not 1 <= args.scan_port <= 65535:
        parser.error("--scan-port must be between 1 and 65535.")

    data_dir = Path(args.data_dir).resolve()
    ensure_recorder_upgrade_config(data_directory=data_dir)
    state_dir = data_dir / "source_state"
    _config, parsed_sources = _prepare_recorder_configuration(
        parser=parser,
        args=args,
        data_dir=data_dir,
        manual_sources=manual_sources,
    )
    config_path = data_dir / "capabilities" / "config.json"
    control_path = state_dir / "mtconnect_recorder_control.json"
    os.environ.update(
        {
            "FCP_RECORDER_MANAGED": "true",
            "FCP_RECORDER_CONFIG_FILE": str(config_path),
            "FCP_RECORDER_CONTROL_FILE": str(control_path),
            "FCP_RECORDER_DATA_DIR": str(data_dir),
            "FCP_RECORDER_STATE_FILE": str(
                state_dir / "mtconnect_recorder_state.json"
            ),
            "FCP_RECORDER_STATUS_FILE": str(
                state_dir / "mtconnect_recorder_status.json"
            ),
            "FCP_RECORDER_LOG_FILE": str(
                state_dir / "mtconnect_recorder.log"
            ),
            "FCP_RECORDER_POLL_INTERVAL": str(args.poll_interval),
            "FCP_RECORDER_BATCH_SIZE": str(args.batch_size),
            "FCP_RECORDER_MAX_BATCHES_PER_CYCLE": str(
                args.max_batches_per_cycle
            ),
            "FCP_RECORDER_REQUEST_TIMEOUT": str(args.timeout),
            "FCP_RECORDER_ONCE": "true" if args.once else "false",
        }
    )

    recorder_path = (
        Path(__file__).resolve().parent
        / "catalog"
        / "standalone-recorder_v2"
        / "standalone-recorder_v2.py"
    )
    if not recorder_path.exists():
        print(f"Recorder script not found: {recorder_path}", file=sys.stderr)
        return 2

    federation_node: RecorderFederationNode | None = None
    federation_control: RecorderFederationControlWorker | None = None
    try:
        try:
            federation_node = _start_federation(
                args=args,
                pairing_key=pairing_key,
                data_dir=data_dir,
                parsed_sources=parsed_sources,
            )
        except (
            AuthenticationError,
            FederationOperationError,
            FederationValidationError,
            OSError,
            RuntimeError,
            TimeoutError,
        ):
            return 3
        finally:
            # Do not leave the one-use key available to the long-running
            # recorder after bootstrap.
            os.environ.pop("FCP_RECORDER_FEDERATION_KEY", None)
            args.federation_key = None
            pairing_key = None

        if federation_node is not None:
            federation_control = RecorderFederationControlWorker(
                federation_node,
                data_directory=data_dir,
            )
            federation_control.start()

        print("Starting loss-aware MTConnect recorder")
        if parsed_sources:
            print("Sources:")
            for name, url in parsed_sources:
                print(f"  {name}: {url}")
        else:
            print(
                "Sources: none selected; recorder is on standby and can be "
                "scanned/configured from any trusted Federation device."
            )
        print(f"Data: {data_dir}")
        print(
            "Press Ctrl+C to stop."
            if not args.once
            else "Running one catch-up cycle."
        )

        # The recorder is environment-configured. Hide launcher arguments --
        # especially the one-use pairing key -- from the nested script.
        original_argv = sys.argv
        try:
            sys.argv = [str(recorder_path)]
            runpy.run_path(str(recorder_path), run_name="__main__")
        finally:
            sys.argv = original_argv
        return 0
    finally:
        if federation_control is not None:
            federation_control.stop()
        if federation_node is not None:
            federation_node.stop()


if __name__ == "__main__":
    raise SystemExit(main())
