"""Capability-specific contracts and deterministic scheduling domain logic."""

from .jobs import (
    ARTIFACT_REFERENCE_SCHEMA,
    ATTEMPT_SCHEMA,
    CAPABILITY_REQUIREMENT_SCHEMA,
    JOBS_PROTOCOL,
    JOBS_PROTOCOL_MAJOR,
    JOBS_PROTOCOL_VERSION,
    JOB_SCHEMA,
    RETRY_POLICY_SCHEMA,
    TIMEOUT_POLICY_SCHEMA,
    ArtifactReference,
    AttemptStatus,
    CapabilityRequirement,
    JobAttempt,
    JobContract,
    JobStatus,
    RetryPolicy,
    TimeoutPolicy,
    protocol_major,
    validate_attempt_transition,
    validate_job_transition,
    validate_jobs_protocol,
)

__all__ = [
    "ARTIFACT_REFERENCE_SCHEMA",
    "ATTEMPT_SCHEMA",
    "CAPABILITY_REQUIREMENT_SCHEMA",
    "JOBS_PROTOCOL",
    "JOBS_PROTOCOL_MAJOR",
    "JOBS_PROTOCOL_VERSION",
    "JOB_SCHEMA",
    "RETRY_POLICY_SCHEMA",
    "TIMEOUT_POLICY_SCHEMA",
    "ArtifactReference",
    "AttemptStatus",
    "CapabilityRequirement",
    "JobAttempt",
    "JobContract",
    "JobStatus",
    "RetryPolicy",
    "TimeoutPolicy",
    "protocol_major",
    "validate_attempt_transition",
    "validate_job_transition",
    "validate_jobs_protocol",
]
