"""Safe, framework-neutral Federation product projections."""

from .adapters import (
    ActivityRecord,
    BenchmarkRecord,
    BenchmarkResultsAdapter,
    BenchmarkSnapshot,
    ContributionRecord,
    DeviceRecord,
    FederatedCapabilityRecord,
    FederationAuthorityAdapter,
    FederationAuthoritySnapshot,
    JobAuthorityAdapter,
    JobAuthoritySnapshot,
    JobRecord,
    OnboardingContractsAdapter,
    OnboardingSnapshot,
    ProviderOperatorAdapter,
    ProviderRecord,
    ProviderSnapshot,
    StorageAuthorityAdapter,
    StorageAuthoritySnapshot,
    StorageGroupRecord,
    StorageProviderRecord,
)
from .models import (
    FederationPage,
    FederationViewModel,
    NoticeKind,
    ProjectionItem,
    ProjectionNotice,
    ProjectionState,
    RecommendedAction,
    SectionLink,
    SummaryCard,
    TechnicalDetail,
)
from .safety import assert_public_projection, is_public_route
from .service import FederationProjectionService, ProjectionAdapters

__all__ = [
    "ActivityRecord",
    "BenchmarkRecord",
    "BenchmarkResultsAdapter",
    "BenchmarkSnapshot",
    "ContributionRecord",
    "DeviceRecord",
    "FederatedCapabilityRecord",
    "FederationAuthorityAdapter",
    "FederationAuthoritySnapshot",
    "FederationPage",
    "FederationProjectionService",
    "FederationViewModel",
    "JobAuthorityAdapter",
    "JobAuthoritySnapshot",
    "JobRecord",
    "NoticeKind",
    "OnboardingContractsAdapter",
    "OnboardingSnapshot",
    "ProjectionAdapters",
    "ProjectionItem",
    "ProjectionNotice",
    "ProjectionState",
    "ProviderOperatorAdapter",
    "ProviderRecord",
    "ProviderSnapshot",
    "RecommendedAction",
    "SectionLink",
    "StorageAuthorityAdapter",
    "StorageAuthoritySnapshot",
    "StorageGroupRecord",
    "StorageProviderRecord",
    "SummaryCard",
    "TechnicalDetail",
    "assert_public_projection",
    "is_public_route",
]
