"""Local device inspection and bounded capability benchmark framework."""

from .adapters import (
    COMPUTE_BENCHMARK_ID,
    COMPUTE_PREREQUISITE,
    MTCONNECT_BENCHMARK_ID,
    MTCONNECT_PREREQUISITE,
    NETWORK_BENCHMARK_ID,
    NETWORK_PREREQUISITE,
    OLLAMA_BENCHMARK_ID,
    OLLAMA_PREREQUISITE,
    STORAGE_BENCHMARK_ID,
    STORAGE_PREREQUISITE,
    AuthenticatedNetworkPathAdapter,
    AuthenticatedPathSample,
    AuthenticatedPathTarget,
    ConcreteAdapterRegistration,
    MtconnectSourceAdapter,
    OllamaBenchmarkAdapter,
    OllamaProbeError,
    OllamaProbeTarget,
    RegisteredComputeHandlerAdapter,
    StorageCandidateAdapter,
    StorageCandidateTarget,
    register_concrete_adapters,
)
from .errors import (
    BenchmarkingError,
    DuplicateBenchmarkError,
    DuplicateRunIdError,
    InvalidBenchmarkOutputError,
    MissingDependencyInputError,
    UnknownBenchmarkError,
)
from .fingerprints import dependency_fingerprint, request_fingerprint
from .inspection import (
    DeviceInspector,
    InspectionContext,
    InspectionFinding,
    InspectionProbe,
)
from .registry import (
    BenchmarkProbe,
    BenchmarkRegistry,
    RegisteredBenchmark,
)
from .runner import (
    BenchmarkCancelled,
    BenchmarkExecutionContext,
    BenchmarkObservation,
    BenchmarkRunner,
    BenchmarkRunRequest,
    CancellationToken,
)
from .safety import (
    bounded_public_mapping,
    safe_diagnostics,
    safe_text,
    sanitize_public_value,
)
from .store import SQLiteBenchmarkResultStore
from .validity import (
    BenchmarkValidity,
    BenchmarkValidityReason,
    evaluate_result,
)

__all__ = [
    "COMPUTE_BENCHMARK_ID",
    "COMPUTE_PREREQUISITE",
    "MTCONNECT_BENCHMARK_ID",
    "MTCONNECT_PREREQUISITE",
    "NETWORK_BENCHMARK_ID",
    "NETWORK_PREREQUISITE",
    "OLLAMA_BENCHMARK_ID",
    "OLLAMA_PREREQUISITE",
    "STORAGE_BENCHMARK_ID",
    "STORAGE_PREREQUISITE",
    "AuthenticatedNetworkPathAdapter",
    "AuthenticatedPathSample",
    "AuthenticatedPathTarget",
    "BenchmarkCancelled",
    "BenchmarkExecutionContext",
    "BenchmarkObservation",
    "BenchmarkProbe",
    "BenchmarkRegistry",
    "BenchmarkRunRequest",
    "BenchmarkRunner",
    "BenchmarkValidity",
    "BenchmarkValidityReason",
    "BenchmarkingError",
    "CancellationToken",
    "ConcreteAdapterRegistration",
    "DeviceInspector",
    "DuplicateBenchmarkError",
    "DuplicateRunIdError",
    "InspectionContext",
    "InspectionFinding",
    "InspectionProbe",
    "InvalidBenchmarkOutputError",
    "MissingDependencyInputError",
    "MtconnectSourceAdapter",
    "OllamaBenchmarkAdapter",
    "OllamaProbeError",
    "OllamaProbeTarget",
    "RegisteredBenchmark",
    "RegisteredComputeHandlerAdapter",
    "SQLiteBenchmarkResultStore",
    "StorageCandidateAdapter",
    "StorageCandidateTarget",
    "UnknownBenchmarkError",
    "bounded_public_mapping",
    "dependency_fingerprint",
    "evaluate_result",
    "register_concrete_adapters",
    "request_fingerprint",
    "safe_diagnostics",
    "safe_text",
    "sanitize_public_value",
]
