"""Machine-neutral operational semantics over canonical MTConnect evidence."""

from .model import (
    BoundaryConfidence,
    BoundaryReason,
    OperationalBoundary,
    canonical_sha256,
)
from .policy import SEGMENTATION_POLICY, device_key
from .roles import (
    DeviceRoleResolution,
    RoleCandidate,
    RoleResolution,
    RoleResolutionStatus,
    SemanticRole,
    resolve_device_roles,
)
from .runs import (
    MachineRun,
    MachineRunError,
    build_machine_runs,
    segment_machine_runs,
    segment_machine_runs_from_reports,
)
from .timeline import (
    AgentSequenceDiscontinuity,
    AgentStreamError,
    AgentStreamReport,
    ContextSnapshot,
    ContextTransition,
    ContextValue,
    DeviceStreamPartition,
    DeviceTimelineReport,
    ExecutionStateSpan,
    TimelineStatus,
    TimestampDiscontinuity,
    build_agent_stream_reports,
    build_device_timeline,
    build_device_timeline_reports,
    partition_agent_stream,
    partition_agent_streams,
)

__all__ = [
    "SEGMENTATION_POLICY",
    "AgentSequenceDiscontinuity",
    "AgentStreamError",
    "AgentStreamReport",
    "BoundaryConfidence",
    "BoundaryReason",
    "ContextSnapshot",
    "ContextTransition",
    "ContextValue",
    "DeviceRoleResolution",
    "DeviceStreamPartition",
    "DeviceTimelineReport",
    "ExecutionStateSpan",
    "MachineRun",
    "MachineRunError",
    "OperationalBoundary",
    "RoleCandidate",
    "RoleResolution",
    "RoleResolutionStatus",
    "SemanticRole",
    "TimelineStatus",
    "TimestampDiscontinuity",
    "build_agent_stream_reports",
    "build_device_timeline",
    "build_device_timeline_reports",
    "build_machine_runs",
    "canonical_sha256",
    "device_key",
    "partition_agent_stream",
    "partition_agent_streams",
    "resolve_device_roles",
    "segment_machine_runs",
    "segment_machine_runs_from_reports",
]
