"""Machine-neutral operational semantics over canonical MTConnect evidence."""

from .policy import SEGMENTATION_POLICY, device_key
from .roles import (
    DeviceRoleResolution,
    RoleCandidate,
    RoleResolution,
    RoleResolutionStatus,
    SemanticRole,
    resolve_device_roles,
)
from .timeline import (
    AgentSequenceDiscontinuity,
    AgentStreamError,
    AgentStreamReport,
    ContextSnapshot,
    ContextTransition,
    ContextValue,
    DeviceStreamPartition,
    DeviceTimelineReport,
    ExecutionStateSpan,
    TimelineStatus,
    TimestampDiscontinuity,
    build_agent_stream_reports,
    build_device_timeline,
    build_device_timeline_reports,
    partition_agent_stream,
    partition_agent_streams,
)

__all__ = [
    "SEGMENTATION_POLICY",
    "AgentSequenceDiscontinuity",
    "AgentStreamError",
    "AgentStreamReport",
    "ContextSnapshot",
    "ContextTransition",
    "ContextValue",
    "DeviceRoleResolution",
    "DeviceStreamPartition",
    "DeviceTimelineReport",
    "ExecutionStateSpan",
    "RoleCandidate",
    "RoleResolution",
    "RoleResolutionStatus",
    "SemanticRole",
    "TimelineStatus",
    "TimestampDiscontinuity",
    "build_agent_stream_reports",
    "build_device_timeline",
    "build_device_timeline_reports",
    "device_key",
    "partition_agent_stream",
    "partition_agent_streams",
    "resolve_device_roles",
]
