import datetime,json
from pathlib import Path
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
root=Path('handoff');p=root/'QUALIFICATION_COORDINATION.md';s=p.read_text(encoding='utf-8');s=s.replace('native log/JUnit reconciliation is next. Preserve','native logs/JUnit are now reconciled (1 of 2 required green runs). Preserve')
s=s.replace('review both F7 runs (34689990990 and34690234286) and their native logs/JUnit.','review queued canary F7 run34690234286 at the next scheduled check; retain the\ncompleted PR468 proof unchanged (diagnostics/ci-f7-pr468-native-proof.json).')
s+='\n## '+now+' — first native replacement proof reviewed and retained\n\n'+'''F7 run34689990990: Linux713 PASS/9 platform skips, Windows717 PASS/5\nsymlink-privilege skips;722 distinct test identities pass across the native pair.\nBoth actual checkouts are b0fbb8a1a4e216b8696b8015a35594c1007319de and\nhave the identical tree of PR468 source f3abe545. Seven exact command invocations,\nPython3.12.13/3.12.10, native shells, Linux storage/Windows long-path preconditions,\nstrictUP035/relay lint, Compose and diff hygiene are verified in logs. All12 mapped\nAI-JavaScript Windows modules, three transfer modules and29 CI-contract checks\npassed without skips on both OS. Every other skip passes on the opposite OS.\nReceipt: diagnostics/ci-f7-pr468-native-proof.json; both original digest-verified\nJUnit ZIPs are retained in diagnostics/ci-f7-native-evidence/. No CI was rerun.\n\nRequired replacement proof:1/2 reviewed green; actual JS-only event proved in\nPR469/run34690234286, native pair still queued at the last bounded snapshot.\nNext scheduled check11:55Z: run diagnostics/inspect_f7_replacement_runs.py with\nthe audit Python -B. If the canary completed, retain its native logs/artifacts\nusing label ci-f7-pr469-run34690234286, then run review_f7_native_proof.py469\n(the CLI requires a space before469). Preserve source/head/synthetic distinctions.\nDo not merge the disposable canary. Preserve automatic PR468/469 companion runs;\ninspect any failures before edits or reruns. Long-run first snapshot was11:05Z;\ndo not repeat long-job checks before11:55Z absent an actionable external event.\nAfter the second native green proof, complete final reference/status-contract and\nretirement-group review before any deletion. All eight legacy files remain.\nProtected Recorder data untouched; no candidate freeze or physical PASS/P07/P12.\n'''
p.write_text(s,encoding='utf-8')
p=root/'CI_COVERAGE_MIGRATION_PLAN.md';s=p.read_text(encoding='utf-8').replace('native equivalence proof pending.','native equivalence proof 1/2 reviewed green; JS-only automatic event verified.');s=s.replace('review PR468 native run34689990990 and create the planned JS-only canary;\nthen obtain two complete source-bound green replacement executions.','preserve the reviewed PR468 native proof and inspect queued JS-only PR469\nrun34690234286 near completion. One of two required native executions is reviewed\ngreen; actual JS-only automatic triggering is proved.');p.write_text(s,encoding='utf-8')
for name in ['ci-migration-equivalence-matrix.json','ci-f7-extension-checkpoint.json']:
 p=root/'diagnostics'/name;o=json.loads(p.read_text())
 if name.startswith('ci-migration'):
  o['status']='STAGE1_ONE_OF_TWO_NATIVE_GREENS_REVIEWED';o['implementation']['native_runs_verified']=1;o['implementation']['native_receipt']='ci-f7-pr468-native-proof.json'
 else:o['native_replacement_executions_verified']=1;o['js_only_automatic_event_verified']=True;o['native_receipt']='ci-f7-pr468-native-proof.json'
 p.write_text(json.dumps(o,indent=2)+'\n',encoding='utf-8')
