"""Bind focused cross-platform evidence to the published repair source."""
import datetime,hashlib,json,pathlib,subprocess,xml.etree.ElementTree as ET,zipfile
root=pathlib.Path('handoff');dest=root/'diagnostics';private=pathlib.Path(r'C:\wsl\fcp-v1-fba508-nettking-20260910\.acceptance');source=pathlib.Path(r'C:\wsl\fcp-fix-d13-windows-refusal-response-20260912')
def git(*args):return subprocess.check_output(['git','-C',str(source),*args],text=True).strip()
assert not git('status','--porcelain')
head=git('rev-parse','HEAD');assert head=='5e6f184311019b9982e8544a18f3dc02c1b16e98'
assert git('rev-parse','HEAD^{tree}')==git('rev-parse','origin/pr475-merge^{tree}')
counts={};raw=[]
for name in ['D13-repair-windows.xml','D13-repair-linux.xml','D13-repair-discovery-windows.xml','D13-fallback-correct-context.xml','D13-baseline-regression.xml']:
    p=private/name;tree=ET.fromstring(p.read_bytes());cases=tree.findall('.//testcase')
    counts[name]={'tests':len(cases),'failures':len(tree.findall('.//failure')),'errors':len(tree.findall('.//error')),'skips':len(tree.findall('.//skipped')),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()};raw.append(p)
assert counts['D13-repair-windows.xml']['tests']==46 and counts['D13-repair-windows.xml']['failures']==0
assert counts['D13-repair-linux.xml']['tests']==46 and counts['D13-repair-linux.xml']['failures']==0
assert counts['D13-fallback-correct-context.xml']['failures']==0
with zipfile.ZipFile(dest/'D13-focused-native-evidence.zip','w',zipfile.ZIP_DEFLATED) as archive:
    for p in raw:archive.write(p,p.name)
e={'recorded_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'repair_sha':head,'synthetic_checkout':git('rev-parse','origin/pr475-merge'),'identical_tree':git('rev-parse','HEAD^{tree}'),'base':'b7194820d8f1940ae60b8c9639e09b7f61e65c55','pr':475,'changed_files':git('diff','--name-only','HEAD^','HEAD').splitlines(),'source_clean':True,'junit':counts,'native_windows':'NETTKING/Martin Python3.12.10,46/46 responderPASS; development source before commit byte-identical to published source','native_linux':'NETTKING Ubuntu WSL Python3.12.13,46/46 responderPASS on clean exact head; disposable constrained venv','windows_discovery':'164unique tests pass across original163pass and one corrected-context fallback test;7platform skips. Original local PATH failure retained, no claim of a single all-green invocation.','lint_syntax_diff':'PASS on unchanged two-file repair','automatic_ci':'Startup confirmed17:09Z; release fixed/rotating suites actively executing. Branding and Linux update completed, native logs retained at synthetic checkout. No manual qualification dispatch.','next_check':'No routine job poll before17:55Z; process completion/failure state changes only. Keep both draft475 and473 heads fixed. D11 remains unresolved.','protected_recorder_data':'UNTOUCHED','physical_runtime':'UNCHANGED; no physical PASS/P07/P12','qualification':'Focused development and automatic PR evidence only; not full release qualification or physical acceptance.'}
(dest/'D13-focused-proof.json').write_text(json.dumps(e,indent=2)+'\n',encoding='utf-8')
p=dest/'D13-evidence.json';data=json.loads(p.read_text(encoding='utf-8'));data['status']='RESOLVED-IN-BRANCH; Windows/Linux focused proof PASS; required CI/review pending';data['next_diagnostic_action']=e['next_check'];data['evidence'].append('D13-focused-proof.json');p.write_text(json.dumps(data,indent=2)+'\n',encoding='utf-8')
p=dest/'D13.md';s=p.read_text(encoding='utf-8').replace('RESOLVED-IN-BRANCH; native Linux and required CI/review pending','RESOLVED-IN-BRANCH; Windows/Linux focused proof PASS, required CI/review pending');s+='\n## '+e['recorded_at']+' — focused native proof complete\n\n[Exact proof](D13-focused-proof.json) and [all native JUnit](D13-focused-native-evidence.zip):46responder tests pass on each native OS; deterministic baseline failure retained. Published head5e6f1843 is clean; automatical PR checkout a5e743fe has identical tree. Broad Windows164uniquePASS/7skips across original and one corrected-PATH test, with original failure retained. Automatic PR475 checks are active, no manual full qualification dispatch. Next check no earlier than17:55Z. No deployment or physical PASS.\n';p.write_text(s,encoding='utf-8')
p=root/'FEDERATION_V1_DIAGNOSTIC_SWEEP.md';s=p.read_text(encoding='utf-8').replace('5e6f1843; Linux/CI/review pending','5e6f1843; native46/46 eachOS PASS, CI/review pending');p.write_text(s,encoding='utf-8')
p=root/'QUALIFICATION_COORDINATION.md';s=p.read_text(encoding='utf-8');start=s.index('**Current actionable checkpoint');end=s.index('Current user direction, September 11 2026:')
new='**Current actionable checkpoint ('+e['recorded_at']+'):** D13 repair is published as draft PR475, exact5e6f184311019b9982e8544a18f3dc02c1b16e98, based on main b7194820. Only responder/test changed. Native Windows3.12.10 and Linux3.12.13 each46/46 responderPASS. New synchronized regression fails on unchanged baseline. Size/deadline/EOF/error coverage and lint/syntax/diff pass. Broader Windows discovery164uniquePASS/7skips across original run plus one corrected child-PATH test; original local environment failure retained. No assertion or source workaround.\n\nAutomatic PR475 checks started normally; release fixed/rotating suites executing at17:09Z. Branding and Linux update completed and native checkout a5e743fee24e27bfd8d6d4f57c8efd589c6c3a42 verified; tree1c671f446fa215c99a6a58a155806de394aa569a equals5e6head. Receipts diagnostics/D13-focused-proof.json and pr475-initial-ci.json. NEXT routine check no earlier than17:55Z, limited to PR475 active required jobs/reviews; preserve head and results. No manual full candidate qualification or duplicate dispatch. D11/#471 remains unresolved and must not be inferred repaired from green runs.\n\nPR473 remains draft/fixed440123f6, with exact F7 final-source native proof, original2/2 replacement proof and real JS-only event retained. Its Windows release retry failed D13, not D12;149PASS/7skips/1fail plus3dependent red aggregates. No further retry. D13 issue474 links original evidence and draft475; no physical observations used for acceptance.\n\nD12 Beast exact safe.directory host correction remains verified under original NETWORK SERVICE; prior launcher failures did not recur on Nettking, which is not original-host CI proof. Keep D10 separate. Main b719 release16/16 proof archived with companion failures. Last fully qualified candidate17ab3a05(37+3) remains; no new candidate freeze or merge yet.\n\nPhysical runtime9b286f93 and protected Recorder data untouched. No physical PASS, P07/P12, deployment, Docker reset/prune or runner/account/pool change. Coordination-only Beast maintenance workflow must never enter a release candidate.\n\n'
p.write_text(s[:start]+new+s[end:],encoding='utf-8')
print(json.dumps({'head':head,'counts':counts,'next':e['next_check']}))
