"""Persist/publish one newly observed CI blocker before investigating another."""
import datetime,hashlib,json,pathlib,subprocess,sys
ROOT=pathlib.Path(__file__).resolve().parents[2];D=ROOT/'handoff/diagnostics';PRIVATE=pathlib.Path(r'C:\wsl\fcp-v1-fba508-nettking-20260910\.acceptance');sys.path.insert(0,str(PRIVATE))
from github_qualification import client
HEAD='ba44100ec1e4cde19daba0d3723b991c11742316';CHECKOUT='f18e91adae2cb198fb5cebad61ee202a38d2bd8e'
DATA={
'D11':{'job':103557723475,'run':34695331201,'host':'AQG7NCC-Linux, runner31','stage':'Linux release regression shard2; no physical stage','title':'ci: live storage reinstatement returns retryable TimeoutError on AQG Linux (D11)','command':'python -m scripts.ci_pytest_shards run --index 2 --count 4 --manifest <runner.temp>/release-shards/shard-2.json -- -o addopts= -q --durations=20 --junitxml=<runner.temp>/release-shards/junit-2.xml','observed':'test_live_reinstatement_restores_replica_and_acknowledgement_policy ends retryable/TimeoutError instead of completed at catalog/node/tests/test_live_storage_reinstatement.py:410; 1 failed,1101 passed,19 skipped,3365 deselected; failing case49.57s.','expected':'The final reinstatement succeeds after the test exercises rollback/retry, restoring replica and acknowledgement policy.','classification':'UNRESOLVED: timeout is confirmed; product, test-harness timing, host load/admission or transient transport cause is not established.','impact':'Release shard2 and dependent aggregates fail on this PR source. Preserve prior main17ab and F7 equivalence evidence; do not call this a documentation regression or physical acceptance.','next':'Retain the failed shard manifest/JUnit and inspect the exact result/timeout boundary in test_live_storage_reinstatement.py and live_storage_reinstatement.py. Check prior native same-test outcomes and AQG31 admission evidence before a focused unchanged-source reproduction. Do not extend deadlines or weaken authority/acknowledgement guards.','needles':['_____ test_live_reinstatement','E           AssertionError:','FAILED catalog/node/tests/test_live_storage_reinstatement','1 failed, 1101 passed','49.57s call'],'excerpt_start':480,'excerpt_end':1328},
'D12':{'job':103557723740,'run':34695331247,'host':'Beast Windows, runner28','stage':'Phase2 Go direct peer sidecar build; no physical stage','title':'ci: Beast Go sidecar build cannot obtain VCS status after passing Go tests (D12)','command':'cd cmd/fcp-peer-sidecar; go mod tidy; go test ./...; New-Item -ItemType Directory -Force -Path ../../build; go build -trimpath -o ../../build/fcp-peer-sidecar.exe .','observed':'Go1.25.7 tests pass (0.191s), then go build fails: error obtaining VCS status: exit status128. Python Phase2 regression step is skipped after the build failure.','expected':'Go build obtains valid Git provenance and produces the sidecar binary, allowing the remaining Phase2 checks to execute.','classification':'UNRESOLVED; host/toolchain Git provenance failure is suspected. Underlying Git stderr is not in the retained build error, and no product test failure was observed.','impact':'Phase2 Windows check blocked. Not the same proven mechanism as D10, although the same runner/workspace may share an environment cause; do not merge those findings without evidence.','next':'Inspect the unchanged workflow/toolchain and same-runner Git cwd/HOME/safe-directory/ownership diagnostics through a read-only channel. Obtain the actual Git error before repair or targeted retry. Do not disable VCS stamping, add broad safe.directory exceptions or change service accounts.','needles':['go version go1.25.7','go build -trimpath','error obtaining VCS status','Use -buildvcs=false','0.191s'],'excerpt_start':420,'excerpt_end':490}
}
def git(*args):return subprocess.check_output(['git','-C',str(ROOT),*args],text=True).strip()
def checkpoint(message):
 subprocess.run(['git','-C',str(ROOT),'add','handoff'],check=True)
 subprocess.run(['git','-C',str(ROOT),'commit','-m',message],check=True,stdout=subprocess.DEVNULL)
 subprocess.run(['git','-C',str(ROOT),'push','origin','codex/federation-v1-diagnostic-sweep-20260911'],check=True,stdout=subprocess.DEVNULL)
 return git('rev-parse','HEAD')
def main():
 fid=sys.argv[1];m=DATA[fid];path=PRIVATE/'pr468-ba44100e-failures-1355-native-logs'/(str(m['job'])+'.log');raw=path.read_bytes();lines=raw.decode('utf-8').splitlines();ret=json.loads((PRIVATE/'pr468-ba44100e-failures-1355-native-retention.json').read_text());rec=next(r for r in ret['records'] if r['job_id']==m['job']);assert rec['checkout_matches'] and hashlib.sha256(raw).hexdigest()==rec['sha256']
 excerpt='\n'.join(lines[m['excerpt_start']:m['excerpt_end']]+[l for l in lines if any(n in l for n in m['needles'])])+'\n';(D/(fid+'-native-excerpt.log')).write_text(excerpt,encoding='utf-8')
 o={'finding':fid,'status':'CONFIRMED_FAILURE_ROOT_CAUSE_UNRESOLVED','recorded_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'candidate_sha':HEAD,'actual_checkout_sha':CHECKOUT,'checkout_tree_identical_to_candidate':True,'host':m['host'],'physical_stage':m['stage'],'command':m['command'],'observed':m['observed'],'expected':m['expected'],'classification':m['classification'],'acceptance_impact':m['impact'],'safe_continuation':'YES: independent read-only/focused diagnosis on unchanged source; no merge or retirement while required failures remain unclassified/unresolved.','evidence':{'run_id':m['run'],'job_id':m['job'],'native_log_receipt':rec,'durable_excerpt':fid+'-native-excerpt.log'},'state_changed':'CI-owned checkout/test fixtures/dependency caches and failed build/test work only; investigation read retained logs. No manual host mutation.','protected_recorder_data':'UNTOUCHED','physical_runtime_sha':'9b286f931497bf6291e215f6340443c5162826b0','github_artifact':'PENDING','repair':'NONE','next_diagnostic_action':m['next']}
 ep=D/(fid+'-evidence.json');ep.write_text(json.dumps(o,indent=2)+'\n',encoding='utf-8')
 fields=[('Finding',fid),('Status','CONFIRMED failure; root cause unresolved'),('Candidate SHA','`'+HEAD+'`; actual checkout `'+CHECKOUT+'` has identical tree.'),('Host(s)',m['host']),('Physical stage',m['stage']),('Observed',m['observed']),('Expected',m['expected']),('Classification',m['classification']),('Acceptance impact',m['impact']),('Safe continuation',o['safe_continuation']),('Evidence','['+fid+'-evidence.json]('+fid+'-evidence.json) and [native excerpt]('+fid+'-native-excerpt.log).'),('GitHub artifact','Publication follows this immediate checkpoint.'),('Repair','NONE'),('Next diagnostic action',m['next'])]
 md='# '+m['title']+'\n\n'+'\n\n'.join('**'+k+':** '+v for k,v in fields)+'\n\nProtected Recorder data and physical runtime were untouched. CI operated only\non its own workspaces. Existing expensive proof is preserved; no rerun or\nproduct change was made to hide this failure.\n';(D/(fid+'.md')).write_text(md,encoding='utf-8')
 table=ROOT/'handoff/FEDERATION_V1_DIAGNOSTIC_SWEEP.md';s=table.read_text(encoding='utf-8');prior='D10' if fid=='D11' else 'D11';pos=s.index('\n',s.index('| '+prior+' |'));s=s[:pos]+'\n| '+fid+' | '+m['stage']+' | '+m['observed']+' | '+m['classification']+' | One exact native failure; focused repro pending | '+m['impact']+' | YES: independent unchanged-source diagnosis | [Evidence](diagnostics/'+fid+'.md); issue publication next; no repair |'+s[pos:];table.write_text(s,encoding='utf-8')
 coord=ROOT/'handoff/QUALIFICATION_COORDINATION.md';s=coord.read_text(encoding='utf-8');s+='\n## '+o['recorded_at']+' — '+fid+' confirmed before deeper diagnosis\n\n'+m['observed']+'\n\n'+m['classification']+'\nExact SHA/logs/procedure and protected-data invariant are persisted in\ndiagnostics/'+fid+'.md. Publish its durable GitHub artifact before further\ninvestigation. '+m['next']+'\n';coord.write_text(s,encoding='utf-8')
 checkpoint_sha=checkpoint('docs: persist '+fid+' exact failure before further investigation')
 api=client();existing=next((i for i in api('/issues?state=open&per_page=100') if i['title']==m['title']),None)
 body=md+'\n[Immutable evidence checkpoint](https://github.com/Nettking/msh/blob/'+checkpoint_sha+'/handoff/diagnostics/'+fid+'.md) and [exact native job](https://github.com/Nettking/msh/actions/runs/'+str(m['run'])+'/job/'+str(m['job'])+').\n\nRelative evidence links in the field list resolve within that checkpoint. Diagnosis must distinguish host/transient/test behavior from product defects before any repair; do not relax contracts to obtain green.\n'
 issue=existing or api('/issues',{'title':m['title'],'body':body});o['github_artifact']=issue['html_url'];ep.write_text(json.dumps(o,indent=2)+'\n',encoding='utf-8');mp=D/(fid+'.md');s=mp.read_text(encoding='utf-8').replace('Publication follows this immediate checkpoint.','[#'+str(issue['number'])+']('+issue['html_url']+').');mp.write_text(s,encoding='utf-8');s=table.read_text(encoding='utf-8').replace('[Evidence](diagnostics/'+fid+'.md); issue publication next; no repair','[Evidence](diagnostics/'+fid+'.md); [#'+str(issue['number'])+']('+issue['html_url']+'); no repair');table.write_text(s,encoding='utf-8');s=coord.read_text(encoding='utf-8')+'\n'+fid+' durable artifact: '+issue['html_url']+'.\n';coord.write_text(s,encoding='utf-8');checkpoint('docs: link durable '+fid+' issue before continuing');print(json.dumps({'finding':fid,'issue':issue['number'],'url':issue['html_url'],'checkpoint':git('rev-parse','HEAD')}))
if __name__=='__main__':main()
