"""Close this diagnostic checkpoint without rerunning completed CI."""
import datetime,json,pathlib,subprocess,zipfile
root=pathlib.Path('handoff');dest=root/'diagnostics';now=datetime.datetime.now(datetime.timezone.utc).isoformat()
observer=json.loads((dest/'D14-D15-focused-observer.json').read_text());assert observer['exitstatus']==0
assert len(observer['observations'])==2 and all(o['outcome']=='passed' for o in observer['observations'])
with zipfile.ZipFile(dest/'D14-D15-focused-evidence.zip','w',zipfile.ZIP_DEFLATED) as archive:
    archive.write(pathlib.Path(r'C:\wsl\fcp-v1-fba508-nettking-20260910\.acceptance\D14-D15-focused.xml'),'D14-D15-focused.xml')
    archive.write(dest/'D14-D15-focused-observer.json','observer.json')
e={'recorded_at':now,'candidate_sha':'5e6f184311019b9982e8544a18f3dc02c1b16e98','focused_result':'2PASS,1warning on NETTKING Ubuntu WSL; one D14 and one D15 test. Pytest deduplicated repeated node arguments; no claim of five D15 executions.','context_limitation':'Different host and isolated selection, without complete rotating-order predecessor history. Neither original failure reproduced or invalidated.','diagnostic_preflight':'Linux Git could not resolve Windows-owned worktree .git path; source provenance was checked using native Windows Git. No source or Git trust configuration change.','native_order':'Rotating seed1702: D14 index491 (after corrupt benchmark-state test); D15 index673 (after fresh product flow restart/expiry test). Exact8predecessor contexts retained in D14-D15-native-order-context.json.','runner_observation':{'AQG7NCC-Linux':{'id':31,'status':'online','busy':False,'labels':['self-hosted','Linux','X64','fcp-test-linux','fcp-docker-linux','aqg7ncc-linux-admission'],'note':'Current labels do not include fcp-linux-fast. Do not readmit or alter labels just because online; no claim about who changed them.'},'Beast':{'id':28,'status':'online','busy':False,'labels':['self-hosted','X64','Windows','fcp-windows','beast-windows','fcp-windows-fast','fcp-test-windows']}},'next_highest_value_action':'Prepare a bounded diagnostic-only original-host D16 run on existing Beast/fcp-windows runner using clean checked-in5e6source and test-owned temporary fixtures; capture ready/leader/quorum evidence at the failing populate boundary without weakening guards. Persist plan before control-workflow changes. Before any AQG diagnostic scheduling, reconcile its current admission-only labels against checked-in runner policy; never restore release-pool labels automatically.','remaining':'D11,D14,D15,D16 root causes unresolved. D13 repaired in draft475; both drafts475/473 remain fixed. No further broad suite retry or candidate qualification.','protected_recorder_data':'UNTOUCHED','physical_runtime':'UNCHANGED; no physical PASS/P07/P12'}
(dest/'pr475-focused-followup.json').write_text(json.dumps(e,indent=2)+'\n',encoding='utf-8')
for identifier in ['D14','D15']:
    p=dest/(identifier+'-evidence.json');data=json.loads(p.read_text(encoding='utf-8'));data['evidence']+=['D14-D15-focused-evidence.zip','D14-D15-native-order-context.json','pr475-focused-followup.json'];data['focused_followup']=e['focused_result']+' '+e['context_limitation'];p.write_text(json.dumps(data,indent=2)+'\n',encoding='utf-8')
    p=dest/(identifier+'.md');s=p.read_text(encoding='utf-8');s+='\n## '+now+' — focused context comparison\n\n'+e['focused_result']+' '+e['context_limitation']+' [Exact observer/order evidence](pr475-focused-followup.json). Preserve original failure and guards; no whole-suite retry.\n';p.write_text(s,encoding='utf-8')
p=root/'QUALIFICATION_COORDINATION.md';s=p.read_text(encoding='utf-8');start=s.index('NEXT: finish bounded D14/D15');end=s.index('D12 Beast exact Git trust host correction verified;')
new='Focused D14/D15 observer finished2PASS on NETTKING Ubuntu WSL; no original failure reproduced, no five-repeat claim (pytest deduplicated node arguments). Different host/order context cannot resolve either blocker. Native order contexts retained: D14 index491, D15 index673 after fresh restart/expiry flow. Current read-only runner snapshot shows AQG online/idle with admission/test labels, without fcp-linux-fast; do not auto-readmit or change labels. Beast remains online/idle with existing beast-windows/fcp-windows. Receipt diagnostics/pr475-focused-followup.json.\n\nNEXT HIGHEST VALUE ACTION: prepare bounded original-Beast D16 diagnostic on clean5e6source and owned fixtures, capturing readiness/leader/quorum at failed population without bypasses. Persist control-workflow plan before changes. For AQG, reconcile current admission labels with checked-in runner policy before scheduling; no automatic label restoration. Both PR4755e6 and PR473440 stay draft/fixed. No CI polls for completed runs, no full suite retry/candidate qualification/merge/deployment.\n\n'
p.write_text(s[:start]+new+s[end:],encoding='utf-8')
assert not subprocess.check_output(['git','-C',r'C:\wsl\fcp-fix-d13-windows-refusal-response-20260912','status','--porcelain'],text=True).strip()
print(json.dumps({'next':e['next_highest_value_action'],'findings':'D14#476,D15#477,D16#478'}))
