"""Retain same-mechanism recurrence before read-only original-host diagnosis."""
import datetime
import hashlib
import json
import pathlib

root=pathlib.Path('handoff');dest=root/'diagnostics'
private=pathlib.Path(r'C:\wsl\fcp-v1-fba508-nettking-20260910\.acceptance')
native=json.loads((private/'main-b719-f6-failure-native-retention.json').read_text())
raw=(private/'main-b719-f6-failure-native-logs/103572678982.log').read_bytes()
assert native['records'][0]['checkout_matches'] and hashlib.sha256(raw).hexdigest()==native['records'][0]['sha256']
log=raw.decode('utf-8');assert 'error obtaining VCS status: exit status 128' in log
lines=log.splitlines();start=next(i for i,l in enumerate(lines) if 'Run go mod tidy' in l)
(dest/'D12-postmerge-f6-native-excerpt.log').write_text('\n'.join(lines[start:])+'\n',encoding='utf-8')
receipt={'recorded_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'finding':'D12','status':'CONFIRMED_RECURRING_ON_ORIGINAL_HOST','candidate_sha':'b7194820d8f1940ae60b8c9639e09b7f61e65c55','host':'BEAST Windows runner28','physical_stage':'None; automatic merged-main F6 Verify Go node-agent boundary','run_id':34701018860,'job_id':103572678982,'procedure':'F6 sidecar directory: go mod tidy; git diff --exit-code -- go.mod go.sum; go test ./...; go build -trimpath .','observed':'Go tests pass cached; Go build fails obtaining VCS status exit128. Same symptom as original Phase2 failure on Beast, now reproduced by another checked-in workflow.','expected':'Default Go VCS stamping obtains Git provenance and build succeeds.','classification':'Host/toolchain Git-context failure; underlying Git stderr/root cause still unresolved. No product test failure observed.','acceptance_impact':'F6 post-merge check fails; no final candidate freeze/qualification completion from this state. PR473 remains draft pending source validation and assessment.','safe_continuation':'YES for independent queued CI and read-only Beast Git-context diagnostics; no additional blind retry, source repair, VCS bypass, workspace cleanup or service-account change.','state_changed':'Only CI-owned workspace/dependency generated files and GitHub failure state; no physical deployment/runner configuration change.','protected_recorder_data':'UNTOUCHED','evidence':native,'github_artifact':'https://github.com/Nettking/msh/issues/472','repair':'NONE','next_diagnostic_action':'Obtain actual Git VCS status stderr under Beast runner28 service identity/cwd/env through a read-only channel when safely accessible. Compare which git.exe Go resolves and repository ownership/HOME/safe-directory context. Do not change account, configuration or stamping to mask failure.'}
(dest/'D12-postmerge-f6-recurrence.json').write_text(json.dumps(receipt,indent=2)+'\n',encoding='utf-8')
p=dest/'D12.md';s=p.read_text(encoding='utf-8');s=s.replace('**Status:** CONFIRMED failure; root cause unresolved','**Status:** CONFIRMED recurring on original Beast host; root cause unresolved');s+='\n## '+receipt['recorded_at']+' — reproduced by post-merge F6 on Beast\n\n[Exact recurrence evidence](D12-postmerge-f6-recurrence.json) binds run34701018860/job103572678982 to merged b7194820. Go tests pass cached, then default-stamped build again fails Git VCS status exit128. This is the same immediate mechanism under another workflow on the original host. No further retry: obtain actual Git stderr/context read-only; preserve existing passing evidence on other hosts. No product repair or protected Recorder access.\n';p.write_text(s,encoding='utf-8')
p=root/'FEDERATION_V1_DIAGNOSTIC_SWEEP.md';s=p.read_text(encoding='utf-8');lines=s.splitlines();lines=[l.replace('One exact native failure; single unchanged-source retry PASS on Nettking, original host cause unresolved','Two native failures on Beast (Phase2 and post-merge F6); retry passed Nettking; Git root cause unresolved') if l.startswith('| D12 |') else l for l in lines];p.write_text('\n'.join(lines)+'\n',encoding='utf-8')
p=root/'QUALIFICATION_COORDINATION.md';s=p.read_text(encoding='utf-8');s+='\n## '+receipt['recorded_at']+' — D12 recurs in post-merge F6; no blind retry\n\nInitial b719/PR473 snapshot found F6 Windows job103572678982 failed on Beast at15:05Z after passing Go tests, same VCS status exit128. Exact logs retained and recurrence recorded under existing issue472, not a duplicate defect. See diagnostics/D12-postmerge-f6-recurrence.json. Native PR473 F7 run34701516368 is queued on both OS; automatic release34701429430/update34701429438 queued/running, branding green. Main b719 automatic jobs remain active with F6 Linux/other completed checks green; preserve them. Next read-only Beast Git-context diagnosis, no source/config/account changes or retries. Next routine queue check15:55Z.\n';p.write_text(s,encoding='utf-8')
print(json.dumps({'finding':receipt['finding'],'status':receipt['status'],'job':receipt['job_id']}))
