"""Preserve actual Git ownership stderr; do not apply a host or product repair."""
import datetime,hashlib,json,pathlib,re,subprocess,zipfile
root=pathlib.Path('handoff');dest=root/'diagnostics';private=pathlib.Path(r'C:\wsl\fcp-v1-fba508-nettking-20260910\.acceptance');repo=pathlib.Path(r'C:\wsl\fcp-ci-phase-workflow-retirement-20260912')
rows=[];excerpts=[]
with zipfile.ZipFile(dest/'D12-ownership-and-launcher-logs.zip','w',compression=zipfile.ZIP_DEFLATED) as z:
    for label,job in [('main-b719-new-failures',103572678961),('pr473-new-failures',103573774515)]:
        receipt=json.loads((private/(label+'-native-retention.json')).read_text());r=next(r for r in receipt['records'] if r['job_id']==job);raw=(private/(label+'-native-logs')/(str(job)+'.log')).read_bytes()
        assert r['checkout_matches'] and hashlib.sha256(raw).hexdigest()==r['sha256'];log=raw.decode();z.writestr(str(job)+'.log',raw)
        if job==103572678961:
            assert 'fatal: detected dubious ownership' in log and 'Beast/nksra' in log and 'S-1-5-20' in log
            lines=log.splitlines();i=next(i for i,l in enumerate(lines) if 'fatal: detected dubious ownership' in l);excerpts.extend(lines[i:i+17])
        else:
            assert '3 failed, 147 passed, 7 skipped' in log and 'The recorder checkout has no readable commit.' in log
        rows.append(r)
merged='0355023f27c4c6886ab6beb48bb9a998b3ab2904';head='440123f6bc6dc358eef3d233236bc14f91af60e0'
trees=[subprocess.check_output(['git','rev-parse',sha+'^{tree}'],cwd=repo,text=True).strip() for sha in [merged,head]];assert trees[0]==trees[1]
(dest/'D12-ownership-stderr.log').write_text('\n'.join(excerpts)+'\n',encoding='utf-8')
out={'recorded_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'finding':'D12','status':'CONFIRMED_HOST_CONFIGURATION_ROOT_CAUSE_FOR_GIT_REJECTION','candidate_shas':['b7194820d8f1940ae60b8c9639e09b7f61e65c55',head],'pr_checkout':merged,'pr_checkout_tree_identical':True,'host':'BEAST native Windows runner28','stages':['Postmerge update-contracts recorder-supervisor smoke','PR473 Discovery authority and bounded startup regressions','Related previously retained Go VCS and F7/F8 diff failures'],'observed':'Actual git rev-parse stderr rejects C:/actions-runner/_work/msh/msh as dubious ownership: owner Beast/nksra SID S-1-5-21-2697059779-2177400912-248823070-1001; executing identity NETWORK SERVICE SID S-1-5-20. Recorder smoke then calls Trim on missing output; PR473 launcher tests fail closed with no readable commit (3failed/147passed/7skipped).','expected':'The authorized CI checkout is recognized under the unchanged runner service identity so native Git provenance reads work. Protected recorder/runtime execution is not involved.','classification':'HOST/ENVIRONMENT configuration defect: repository ownership/trust mismatch is explicitly confirmed. It explains the shared Git-provenance boundary; do not assert every prior unrelated error has the same cause without evidence.','acceptance_impact':'Blocks native Beast Go/provenance/diff/supervisor checks and PR473 Windows release check. Does not invalidate otherwise-proven command/OS/trigger equivalence or turn successful tests into failures. PR473 remains draft pending resolution of its required check.','safe_continuation':'YES: preserve independent CI evidence and prepare controlled original-host repair. No further blind retry or global wildcard trust bypass.','state_changed':'No host repair, account/ownership/trust change, source/workflow modification, deployment or protected-data access. Only CI evidence retained.','protected_recorder_data':'UNTOUCHED','github_artifact':'https://github.com/Nettking/msh/issues/472','repair':'NONE APPLIED','next_diagnostic_action':'Plan a narrowly scoped repair for the CI-owned checkout under the actual NETWORK SERVICE runner identity, preserving the service account and ownership safety checks. Verify current exact resolved checkout, owner and global Git context first. Use only an authenticated/authorized original-host execution channel; SSH identity/account request remains pending if needed for repair. Retry only affected failed checks after a demonstrated correction.','evidence':rows,'durable_logs':'D12-ownership-and-launcher-logs.zip','actual_stderr':'D12-ownership-stderr.log'}
(dest/'D12-confirmed-ownership-root-cause.json').write_text(json.dumps(out,indent=2)+'\n',encoding='utf-8')
p=dest/'D12.md';s=p.read_text(encoding='utf-8');a=s.index('**Status:**');b=s.index('\n\n',a);s=s[:a]+'**Status:** CONFIRMED host configuration defect: native Git rejects mismatched CI checkout ownership'+s[b:];a=s.index('**Classification:**');b=s.index('\n\n',a);s=s[:a]+'**Classification:** HOST/ENVIRONMENT. Actual Git stderr proves the checkout is owned by Beast/nksra while the runner executes as NETWORK SERVICE (S-1-5-20), and Git rejects it as dubious ownership. See [root-cause evidence](D12-confirmed-ownership-root-cause.json).'+s[b:];s+='\n## '+out['recorded_at']+' — ownership/trust mismatch confirmed\n\n[Actual Git stderr](D12-ownership-stderr.log) and [source-specific logs](D12-confirmed-ownership-root-cause.json) now establish the original-host configuration failure. PR473 launcher tests fail closed at the same readable-commit guard. No product repair, host change or additional retry was made. Original SSH access question remains relevant only if needed for controlled host correction, not to establish this observed cause.\n';p.write_text(s,encoding='utf-8')
p=root/'FEDERATION_V1_DIAGNOSTIC_SWEEP.md';s=p.read_text(encoding='utf-8');lines=s.splitlines();lines=[('| D12 | Native Windows Git provenance/diff/recorder CI guards | Git rejects CI checkout owned by Beast/nksra under NETWORK SERVICE; actual dubious-ownership stderr retained | Host/environment configuration | Repeated Beast failures across Go, F7/F8 diff, update smoke and PR473 launcher guards | Beast native CI and PR473 Windows release check | YES: independent CI; controlled original-host correction required | [Evidence](diagnostics/D12-confirmed-ownership-root-cause.json); [#472](https://github.com/Nettking/msh/issues/472); no repair applied |' if l.startswith('| D12 |') else l) for l in lines];p.write_text('\n'.join(lines)+'\n',encoding='utf-8')
p=root/'QUALIFICATION_COORDINATION.md';s=p.read_text(encoding='utf-8')+'\n## '+out['recorded_at']+' — D12 host ownership cause confirmed\n\nUpdate-smoke job103572678961 exposes actual Git dubious-ownership stderr: CI path owned by Beast/nksra, runner is NETWORK SERVICE S-1-5-20. PR473 Windows release job103573774515 fails three launcher tests at unreadable-commit guard; exact synthetic0355023f tree equals440123f6. Source-specific evidence/complete logs pushed in diagnostics/D12-confirmed-ownership-root-cause.json. D12 is host/environment configuration, no product repair. Plan only a controlled narrow CI-workspace trust/ownership correction under the unchanged runner identity; no action applied, no wildcard bypass or account change. Next classify the remaining AQG Phase2 failure before repair decisions.\n';p.write_text(s,encoding='utf-8');print(json.dumps({'finding':'D12','classification':'HOST_CONFIGURATION_CONFIRMED','owner':'Beast/nksra','runner_sid':'S-1-5-20'}))
