"""Preserve a second reinstatement failure without asserting the same exception."""
import datetime,hashlib,json,pathlib,zipfile
root=pathlib.Path('handoff');dest=root/'diagnostics';private=pathlib.Path(r'C:\wsl\fcp-v1-fba508-nettking-20260910\.acceptance')
ret=json.loads((private/'main-b719-new-failures-native-retention.json').read_text());r=next(r for r in ret['records'] if r['job_id']==103572679008)
raw=(private/'main-b719-new-failures-native-logs/103572679008.log').read_bytes();assert r['checkout_matches'] and hashlib.sha256(raw).hexdigest()==r['sha256'];log=raw.decode();assert 'test_live_reinstatement_restores_replica_and_acknowledgement_policy' in log and '1 failed, 380 passed, 1 skipped' in log
with zipfile.ZipFile(dest/'D11-aqg-windows-phase2-log.zip','w',compression=zipfile.ZIP_DEFLATED) as z:z.writestr('103572679008.log',raw)
lines=log.splitlines();i=next(i for i,l in enumerate(lines) if '== FAILURES ==' in l);(dest/'D11-aqg-windows-phase2-excerpt.log').write_text('\n'.join(lines[i:])+'\n',encoding='utf-8')
out={'recorded_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'finding':'D11','status':'CONFIRMED_RECURRING_TEST_FAILURE_ROOT_CAUSE_UNRESOLVED','candidate_sha':ret['source_commit'],'host':'AQG7NCC-Windows native runner30; same physical AQG machine as original Linux failure','physical_stage':'None; Phase2 Identity/state/protocol/relay/Phase F CI selection','run_id':34701018877,'job_id':r['job_id'],'test':'catalog/node/tests/test_live_storage_reinstatement.py::test_live_reinstatement_restores_replica_and_acknowledgement_policy','stage_in_test':'Tail catch-up precondition assertion at line361; earlier than original line410 final-success failure','observed':'outcome.result.code is live-reinstatement-retryable rather than reinstatement-tail-catchup-required. Suite1failed/380passed/1skipped in303.23s. Underlying exception reason is not exposed by this assertion output.','expected':'Missing tail fence yields the specific catch-up-required code, preserving authority and acknowledgement policy.','classification':'UNRESOLVED product/harness/environment interaction. Same test/retryable result family as D11 on the same physical AQG host; do not assert the original TimeoutError or identical root cause without evidence.','acceptance_impact':'Postmerge Phase2 Windows fails; retain all passing same-source evidence but do not treat a different-host pass as repair.','safe_continuation':'YES: independent CI/read-only source and existing-artifact comparison. No guard/deadline weakening or further blind retry.','command_or_procedure':'Run the checked-in Phase2 workflow test selection; full command and traceback retained in native log.','state_changed':'CI-owned test temporary SQLite/loopback fixtures only. No product source, host configuration or physical deployment.','protected_recorder_data':'UNTOUCHED','github_artifact':'https://github.com/Nettking/msh/issues/471','repair':'NONE','next_diagnostic_action':'Compare already-retained b719 full-suite/Windows transport JUnit outcomes and source path for line361. Record missing exception detail separately; a focused reproduction must expose the retryable reason and preserve original timing/authority guards, without repeating successful qualification jobs.','evidence':r,'durable_log':'D11-aqg-windows-phase2-log.zip'}
(dest/'D11-aqg-windows-phase2-recurrence.json').write_text(json.dumps(out,indent=2)+'\n',encoding='utf-8')
p=dest/'D11.md';s=p.read_text(encoding='utf-8')+'\n## '+out['recorded_at']+' — same test fails on AQG native Windows\n\n[Exact recurrence](D11-aqg-windows-phase2-recurrence.json) binds Phase2 run34701018877/job103572679008 to merged b7194820. The test now fails earlier at line361, returning generic retryable rather than the expected catch-up-required code. This traceback does not expose the exception reason; do not label it TimeoutError without proof. Same physical AQG machine as the earlier Linux failure, but a shared root cause is still unproven. No retry/repair applied.\n';p.write_text(s,encoding='utf-8')
p=root/'FEDERATION_V1_DIAGNOSTIC_SWEEP.md';s=p.read_text(encoding='utf-8');lines=s.splitlines();lines=[('| D11 | Live reinstatement regression on AQG Linux and Windows CI | Unexpected retryable result: original final-success TimeoutError, later tail-catchup code mismatch at line361 | Unresolved product/harness/environment | Same test failed on both AQG OS contexts; underlying cause of second failure not exposed | Release/Phase2 checks on affected attempts; no physical acceptance | YES: independent CI and existing-evidence diagnosis; no blind retry | [Evidence](diagnostics/D11-aqg-windows-phase2-recurrence.json); [#471](https://github.com/Nettking/msh/issues/471); no repair |' if l.startswith('| D11 |') else l) for l in lines];p.write_text('\n'.join(lines)+'\n',encoding='utf-8')
p=root/'QUALIFICATION_COORDINATION.md';s=p.read_text(encoding='utf-8')+'\n## '+out['recorded_at']+' — AQG Windows Phase2 failure retained under D11\n\nJob103572679008 on exact b7194820 fails the same reinstatement test, now at tail-catchup assertion line361: generic retryable instead of catch-up-required. Suite1failed/380passed/1skip. Underlying exception reason is not printed, so common TimeoutError/root cause is not asserted. Evidence/complete log in diagnostics/D11-aqg-windows-phase2-recurrence.json. Original issue471 remains open; no second blind retry. All newly completed failures are now classified by observed mechanism (D11 unresolved, D12 host ownership); no new independent product defect established.\n';p.write_text(s,encoding='utf-8');print(json.dumps({'finding':'D11','stage':'line361 tail-catchup boundary','reason':'UNAVAILABLE_IN_TRACEBACK'}))
