"""Persist read-only access limits and distinguish observations from hypotheses."""
import datetime
import json
import pathlib
import sys

root=pathlib.Path('handoff');dest=root/'diagnostics'
sys.path.insert(0,r'C:\wsl\fcp-v1-fba508-nettking-20260910\.acceptance')
from github_qualification import client
api=client();snap=json.loads((dest/'pr473-initial-native-progress.json').read_text())
portal=next(r for r in snap['runs'] if r['id']==34701429475)
billing=[]
for j in portal['jobs']:
    assert not j['steps'] and not j['runner_name']
    check_id=int(j['check_run_url'].rsplit('/',1)[1]);annotations=api('/check-runs/'+str(check_id)+'/annotations')
    assert any('spending limit' in a.get('message','').lower() for a in annotations)
    billing.append({'job_id':j['id'],'step_count':0,'runner':j['runner_name'],'annotations':annotations})
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
receipt={'recorded_at':now,'finding':'D12','status':'RECURRENCE_PERSISTED_READ_ONLY_HOST_ACCESS_PENDING_TRUSTED_IDENTITY','candidate_sha':'b7194820d8f1940ae60b8c9639e09b7f61e65c55','host':'Beast Windows runner28','confirmed_observations':['Checkout and cleanup use native Git successfully in the repository root. Initial checkout resolves C:/Program Files/Git/cmd/git.exe, later setup adds Git/bin to PATH, and cleanup resolves Git/bin/git.exe.','During F6 sidecar step, git diff --exit-code -- go.mod go.sum outputs diff --git a/go.mod b/go.sum. This compares the two files, rather than a tracked-file working-tree delta.','Go test passes, but default-stamped Go build reports VCS status exit128. Same original host fails both Phase2 and F6.'],'hypotheses_not_confirmed':['Git repository discovery or safe-directory/ownership context differs under the sidecar/native step.','PATH resolution, HOME/global config scope or a concurrent host filesystem context contributes.','PowerShell continuation after an earlier native command failure may conceal additional harness effects; no independent defect/repair is established by this observation.'],'read_only_access':{'tailscale_dns':'beast.tail4ccd2b.ts.net','tailscale_ipv4':'100.85.20.75','online':True,'attempt':'ssh -o BatchMode=yes -o ConnectTimeout=8 -o StrictHostKeyChecking=yes -o LogLevel=ERROR Martin@beast.tail4ccd2b.ts.net whoami','observed':'No ED25519 host key is known; Host key verification failed. Authentication not reached. Martin account remains unverified.','existing_known_host_aliases_found':[],'scanned_untrusted_fingerprint':'SHA256:Dnx+GNIif4iX8N7Xy6slA8Oys4FK2J+P5gan1NTmvmY','question_pending':'User asked asynchronously to verify fingerprint from a trusted Beast context and provide SSH account. Do not treat a scanned key alone as verification.'},'state_changed':'No SSH session, trust-store modification, remote command, runtime deployment, runner config/account or protected-data access. Public host key scanned only.','protected_recorder_data':'UNTOUCHED','next_action':'Continue independent PR473 validation. If trusted Beast identity/account is provided, obtain read-only Git executable/cwd/HOME/safe-directory/ownership and git status stderr under actual runner identity; do not equate an unrelated interactive account with runner context. No further blind retry.','pr473_known_hosted_failure':{'run_id':34701429475,'classification':'Existing hosted billing/admission infrastructure failure before execution; no product failure','jobs':billing}}
(dest/'D12-read-only-access-and-hypotheses.json').write_text(json.dumps(receipt,indent=2)+'\n',encoding='utf-8')
p=dest/'D12.md';s=p.read_text(encoding='utf-8');s+='\n## '+now+' — original-host access and hypotheses persisted\n\n[Read-only access record](D12-read-only-access-and-hypotheses.json) records a repository-discovery clue: the F6 Git diff compares go.mod directly with go.sum. Git/ownership/HOME/PATH causes remain hypotheses. SSH reached host-key verification only; no trusted key is configured. A user question for trusted fingerprint/account is pending while independent PR473 CI continues. No remote command, trust-store or host configuration change.\n';p.write_text(s,encoding='utf-8')
p=root/'QUALIFICATION_COORDINATION.md';s=p.read_text(encoding='utf-8');s+='\n## '+now+' — access limit, hypotheses and next polling boundary\n\nD12 actual Git stderr remains unavailable. SSH to confirmed Tailscale Beast stopped before authentication because no trusted host key is configured. A concise user question for verified fingerprint/account is pending; scanned public key and exact command are in diagnostics/D12-read-only-access-and-hypotheses.json. No host-key policy/configuration was bypassed. Original-host diagnosis can resume on trusted access; PR473 validation continues independently. Git no-index-like diff/PATH/HOME/ownership explanations are hypotheses, not new confirmed product defects.\n\nPR473 docs-portal34701429475 is the known spending-limit admission failure: both jobs have zero steps/no runner, verified annotations. Native branding green. Current-source snapshots were last read15:12Z; review scoped F7 near15:55Z. Do not repoll long release jobs before15:58Z (45minutes after first snapshot); if an hourly heartbeat fires earlier, leave them until a later due check unless an actionable completion/failure is independently delivered. All source branches/checkpoints are pushed. PR473 remains draft at440123f6.\n';p.write_text(s,encoding='utf-8');print(json.dumps({'receipt':'D12-read-only-access-and-hypotheses.json','access':'AWAIT_TRUSTED_IDENTITY','independent_ci':'CONTINUE','hosted_failure':'BILLING_ADMISSION_ZERO_STEPS'}))
