"""Add direct Git discovery evidence to existing D12 without assuming its cause."""
import datetime, hashlib, json, pathlib, re, zipfile
root=pathlib.Path('handoff');dest=root/'diagnostics';private=pathlib.Path(r'C:\wsl\fcp-v1-fba508-nettking-20260910\.acceptance')
ret=json.loads((private/'main-b719-new-failures-native-retention.json').read_text());records=[];excerpts=[]
with zipfile.ZipFile(dest/'D12-f7-f8-git-discovery-logs.zip','w',compression=zipfile.ZIP_DEFLATED) as z:
    for job in [103572679035,103572679136]:
        record=next(r for r in ret['records'] if r['job_id']==job);raw=(private/'main-b719-new-failures-native-logs'/(str(job)+'.log')).read_bytes()
        assert record['checkout_matches'] and hashlib.sha256(raw).hexdigest()==record['sha256']
        log=raw.decode();assert 'warning: Not a git repository.' in log and 'exit code 129' in log
        summaries=re.findall(r'\b\d+ passed, \d+ skipped[^\r\n]*',log);assert summaries
        records.append({**record,'test_summaries':summaries});z.writestr(str(job)+'.log',raw)
        lines=log.splitlines();i=next(i for i,l in enumerate(lines) if '##[group]Run git diff --check' in l);excerpts.extend(lines[i:i+12])
(dest/'D12-f7-f8-git-discovery-excerpt.log').write_text('\n'.join(excerpts)+'\n',encoding='utf-8')
out={'recorded_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'finding':'D12','status':'CONFIRMED_HOST_GIT_DISCOVERY_FAILURE_ROOT_CAUSE_OPEN','candidate_sha':ret['source_commit'],'host':'Beast native Windows runner28','physical_stage':'None; F7/F8 Diff hygiene CI steps','command':'git diff --check origin/main...HEAD','observed':'F7/F8 native tests and prior steps pass, then Git reports Not a git repository and exits129. Checkout/cleanup Git commands work.','expected':'The checked-out repository remains discoverable for final diff verification.','classification':'Host/environment Git execution-context failure. Actual ownership/HOME/PATH/filesystem cause remains unconfirmed. Related to D12 provenance boundary; do not assert a shared root cause with D10.','acceptance_impact':'Postmerge F7/F8 checks fail; tests are not reclassified as product failures. Preserve separately passing equivalent checks on other native hosts.','safe_continuation':'YES: independent CI and read-only diagnosis; no additional retries or source/guard changes.','state_changed':'CI-owned workspaces only; no host configuration, physical runtime, trust-store or protected-data change.','protected_recorder_data':'UNTOUCHED','evidence':records,'durable_logs':'D12-f7-f8-git-discovery-logs.zip','github_artifact':'https://github.com/Nettking/msh/issues/472','repair':'NONE','next_diagnostic_action':'Pending trusted SSH identity/account: inspect Git executable, cwd, repository ownership, HOME/global configuration and git status stderr under Beast runner28 context. Do not bypass stamping or safe-directory guards.'}
(dest/'D12-f7-f8-git-discovery.json').write_text(json.dumps(out,indent=2)+'\n',encoding='utf-8')
p=dest/'D12.md';s=p.read_text(encoding='utf-8')+'\n## '+out['recorded_at']+' — direct Git discovery failure in F7/F8\n\n[Native evidence](D12-f7-f8-git-discovery.json): both Beast postmerge F7/F8 test selections pass, then final Git diff reports Not a git repository, exit129. This establishes the failed repository-discovery boundary explicitly; ownership/HOME/PATH root cause remains unverified. Recorded under existing D12, with no new retry or product repair.\n';p.write_text(s,encoding='utf-8')
p=root/'QUALIFICATION_COORDINATION.md';s=p.read_text(encoding='utf-8')+'\n## '+out['recorded_at']+' — F7/F8 failures classified as D12 Git context\n\nBeast jobs103572679136/103572679035 passed their native tests and failed final Git diff with explicit Not a git repository exit129. Evidence and full logs are preserved in diagnostics/D12-f7-f8-git-discovery.json. This narrows D12 to a failing native Git discovery context; exact cause remains open. No retry/source change. Continue classifying the other completed failed jobs individually.\n';p.write_text(s,encoding='utf-8')
print(json.dumps({'finding':'D12','new_job_evidence':[r['job_id'] for r in records]}))
