"""Keep focused development evidence and local PATH precondition distinct."""
import datetime,json,pathlib,subprocess,zipfile
dest=pathlib.Path('handoff/diagnostics');private=pathlib.Path(r'C:\wsl\fcp-v1-fba508-nettking-20260910\.acceptance');source=pathlib.Path(r'C:\wsl\fcp-fix-d13-windows-refusal-response-20260912')
for name in ['D13-repair-windows.xml','D13-repair-discovery-windows.xml']:(dest/name).write_bytes((private/name).read_bytes())
e={'recorded_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'base_sha':'b7194820d8f1940ae60b8c9639e09b7f61e65c55','development_source':'uncommitted two-file isolated D13 repair; exact diff retained','focused_windows':'46PASS in7.15s','lint':'two changed files RuffPASS','syntax':'both changed Python files ast.parsePASS','discovery_windows':'163PASS,7skips,1failed local precondition: fallback Python absent from PATH after test deliberately blocks its explicit interpreter. Absolute test invocation used venvPython3.12, but PATH resolves Python3.14 first and does not contain that venv. CI action normally prepends venv Scripts.','failure_test':'catalog/mtconnect_recorder/tests/test_tailscale_recorder_launcher.py::test_windows_probe_rejects_runtime_that_cannot_import_exact_entrypoint','classification':'LOCAL DEVELOPMENT ENVIRONMENT; controlled single-test validation with child-only CI-equivalent venv PATH next. No source repair for this observation.','state_changed':'Only development source and ephemeral tests/evidence; no global environment or host configuration change','protected_recorder_data':'UNTOUCHED','qualification':False,'next':'Retry only this failed fallback test with the testing venv on child PATH, preserve original failure; create disposable WSL Python3.12.13 venv for native responder module proof.'}
(dest/'D13-development-progress.json').write_text(json.dumps(e,indent=2)+'\n',encoding='utf-8')
diff=subprocess.check_output(['git','-C',str(source),'diff'],text=True)
with zipfile.ZipFile(dest/'D13-development-repair.zip','w',zipfile.ZIP_DEFLATED) as archive:
    archive.writestr('D13-development-repair.patch',diff)
with pathlib.Path('handoff/QUALIFICATION_COORDINATION.md').open('a',encoding='utf-8') as f:f.write('\n## '+e['recorded_at']+' — D13 focused repair proof and local PATH precondition\n\nIsolated two-file development repair passes46native Windows responder tests and Ruff/syntax. Expanded discovery has163PASS/7skips plus one unrelated launcher fallback failure: local invocation did not put the testing venv on PATH as CI does. Preserve diagnostics/D13-development-progress.json, both XMLs and development diff. Next retry only that failed test with child-only correct PATH; native Linux focused proof then commit/push/draftPR. No PR473/product-runtime/host-config change.\n')
