"""Review actual before/after host evidence before allowing a targeted CI retry."""
import datetime,hashlib,json,pathlib,shutil,zipfile
root=pathlib.Path('handoff');dest=root/'diagnostics';private=pathlib.Path(r'C:\wsl\fcp-v1-fba508-nettking-20260910\.acceptance')
native=json.loads((private/'D12-maintenance-native-retention.json').read_text());art=json.loads((private/'D12-maintenance-raw-artifact-retention.json').read_text());assert len(native['records'])==len(art['records'])==1
a=art['records'][0];zip_path=private/'D12-maintenance-raw-artifacts'/(str(a['id'])+'.zip');assert 'sha256:'+hashlib.sha256(zip_path.read_bytes()).hexdigest()==a['digest']
with zipfile.ZipFile(zip_path) as z:
    assert z.namelist()==['d12-git-context-34704678898.json'];audit=json.loads(z.read(z.namelist()[0]))
assert audit['control_workflow_sha']==native['source_commit']==a['api_workflow_head']
assert audit['status']=='EXACT_CI_WORKSPACE_GIT_TRUST_VERIFIED' and audit['runner']=='Beast' and audit['computer']=='BEAST' and audit['sid']=='S-1-5-20'
assert audit['state_changed'] is True and audit['protected_recorder_data']=='UNTOUCHED'
assert audit['plain_git_before']['exit_code']!=0 and 'dubious ownership' in audit['plain_git_before']['output']
assert audit['global_trust_after']==audit['global_trust_before']+['C:/actions-runner/_work/msh/msh']
assert len(audit['plain_git_after'])==4 and audit['diff_hygiene']['exit_code']==0
assert all(v['result']['exit_code']==0 and v['result']['output'].strip()==audit['existing_checkout_sha'] for v in audit['plain_git_after'])
raw=(private/'D12-maintenance-native-logs/103582477854.log').read_bytes();assert hashlib.sha256(raw).hexdigest()==native['records'][0]['sha256']
assert native['records'][0]['checkout_matches'] is None # The maintenance job intentionally performs no checkout.
shutil.copyfile(zip_path,dest/'D12-verified-host-repair-artifact.zip')
(dest/'D12-verified-host-repair-audit.json').write_text(json.dumps(audit,indent=2)+'\n',encoding='utf-8')
with zipfile.ZipFile(dest/'D12-verified-host-repair-native-log.zip','w',compression=zipfile.ZIP_DEFLATED) as z:z.writestr('103582477854.log',raw)
out={'recorded_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'finding':'D12','status':'HOST_CONFIGURATION_REPAIRED_AND_VERIFIED_AFFECTED_CI_CHECK_PENDING','control_workflow_sha':audit['control_workflow_sha'],'existing_ci_checkout_sha':audit['existing_checkout_sha'],'run_id':34704678898,'job_id':103582477854,'host':'BEAST native runner28','identity_sid':audit['sid'],'before_error':'Actual dubious-ownership rejection under NETWORK SERVICE','exact_change':'Added only C:/actions-runner/_work/msh/msh to the existing NETWORK SERVICE global safe.directory list. All prior entries preserved.','after':'Four plain Git provenance reads succeed (cmd/bin Git, repository/sidecar directories), same existing checkout SHA; plain diff hygiene passes. No per-command trust override used for these validation reads.','no_changes':['Service account','Ownership/ACLs','Runner labels/pools','Worktree checkout/source','PR473 head','Product/runtime state','Protected Recorder data','VCS stamping/CI assertions/deadlines'],'native_retention':native,'artifact':a,'audit':'D12-verified-host-repair-audit.json','safe_continuation':'YES: after current run completes, rerun only failed PR473 Windows release check103573774515 on unchanged head440123f6. No successful jobs or original2/2 replacement proof repeated. Keep earlier-source failures archived.','repair_scope':'Coordination-only maintenance workflow, excluded from release/candidate branches. SSH trust/credentials were not required and no SSH session opened.','physical_acceptance':False,'protected_recorder_data':'UNTOUCHED'}
(dest/'D12-host-repair-reviewed.json').write_text(json.dumps(out,indent=2)+'\n',encoding='utf-8')
p=dest/'D12.md';s=p.read_text(encoding='utf-8');aidx=s.index('**Status:**');bidx=s.index('\n\n',aidx);s=s[:aidx]+'**Status:** HOST CONFIGURATION REPAIRED AND VERIFIED on Beast; affected PR473 CI check pending'+s[bidx:];aidx=s.index('**Repair:**');bidx=s.index('\n\n',aidx);s=s[:aidx]+'**Repair:** Exact CI checkout trust entry added under unchanged NETWORK SERVICE identity by reviewed maintenance run34704678898. [Before/after audit](D12-host-repair-reviewed.json). No candidate source or account change.'+s[bidx:];s+='\n## '+out['recorded_at']+' — host correction verified on actual Beast identity\n\n[Reviewed evidence](D12-host-repair-reviewed.json) contains actual before/after state: one exact global trust entry added, four plain Git source reads and diff hygiene pass on the same existing CI checkout. No wildcard/ownership/account/worktree change. Next only the affected PR473 failed Windows release check may be rerun, after its enclosing run is complete. Keep original failures and D11 distinct; no physical PASS.\n';p.write_text(s,encoding='utf-8')
p=root/'FEDERATION_V1_DIAGNOSTIC_SWEEP.md';s=p.read_text(encoding='utf-8');s=s.replace('no repair applied |','[Host repair verified](diagnostics/D12-host-repair-reviewed.json); affected CI pending |');p.write_text(s,encoding='utf-8')
p=root/'D12_BEAST_CI_HOST_REPAIR.md';s=p.read_text(encoding='utf-8');s=s.replace('Status: PLANNED, not applied.','Status: APPLIED AND VERIFIED on actual Beast NETWORK SERVICE identity; affected CI check pending.');s+='\nActual reviewed run34704678898/job103582477854: see diagnostics/D12-host-repair-reviewed.json. The workflow control SHA and unchanged existing CI checkout SHA are separately recorded.\n';p.write_text(s,encoding='utf-8')
p=root/'QUALIFICATION_COORDINATION.md';s=p.read_text(encoding='utf-8')+'\n## '+out['recorded_at']+' — D12 host correction verified\n\nActual Beast NETWORK SERVICE job34704678898/103582477854 added one exact CI safe.directory entry, preserving prior values. Four plain Git root/sidecar cmd/bin reads and diff hygiene now pass at unchanged existing checkout '+audit['existing_checkout_sha']+'. No checkout/deployment/runner-account/ACL change or protected-data access. Evidence: diagnostics/D12-host-repair-reviewed.json. SSH confirmation is no longer needed for this repair. Next confirm the current PR473 release run is complete before retrying only its affected failed Windows check103573774515; no active job interruption and no successful-job rerun.\n';p.write_text(s,encoding='utf-8')
print(json.dumps({'status':out['status'],'host':out['host'],'source':audit['existing_checkout_sha'],'trust_before':audit['global_trust_before'],'trust_after':audit['global_trust_after']}))
