"""Pure domain contracts for federated MSH sessions."""

from .errors import FederationValidationError
from .filesystem_storage import FilesystemRecorderStorageProvider
from .local_storage import BatchStorageProvider, FilesystemBatchStorageProvider, LocalStorageService
from .logical_storage import (
    CallableStorageTransport,
    LogicalStorageClient,
    RelayNodeStorageTransport,
    StorageRequestTransport,
    StorageRoute,
    StorageRouteResolver,
)
from .outbox import OutboxEntry, OutboxState, SQLiteOutbox
from .postgres_storage import PostgreSQLBatchStorageProvider
from .providers import (
    CapabilityProvider,
    ProviderError,
    ProviderErrorCode,
    StorageProvider,
    StorageReadOutcome,
    StorageWriteOutcome,
)
from .registry import LocalCapabilityRegistry
from .leader_selection import (
    LeaderSelectionResult,
    StorageGroupPolicy,
    select_storage_leader,
    validate_primary_write,
)
from .models import (
    CapabilityAnnouncement,
    CapabilityStatus,
    CommitState,
    DatasetCoverage,
    LeadershipGrant,
    NodeIdentity,
    Session,
    SessionEvent,
    SessionState,
    StorageBatch,
    StorageGroupState,
    StorageManifest,
    StorageNodeState,
    StorageRole,
    StorageWriteRequest,
)
from .storage_control_plane import (
    STORAGE_ASSIGNMENT_CHANGED,
    STORAGE_GROUP_CREATED,
    STORAGE_LEADER_GRANTED,
    STORAGE_LEADER_REVOKED,
    STORAGE_PROVIDER_REGISTERED,
    STORAGE_PROVIDER_REMOVED,
    StorageControlPlaneSnapshot,
    StorageControlPlaneStore,
    StorageGroupAssignment,
    StorageProviderRegistration,
)
from .storage_protocol import (
    STORAGE_PROTOCOL,
    STORAGE_PROTOCOL_MAJOR,
    STORAGE_PROTOCOL_VERSION,
    BatchIngestRequest,
    BatchIngestResult,
    BatchIngestState,
    StorageError,
    StorageErrorCode,
    StorageOperation,
    StorageRequestEnvelope,
    StorageResponseEnvelope,
    WriteAuthority,
    classify_idempotent_ingest,
    validate_protocol_version,
)
from .write_authority import AuthorizedStorageService, StorageWriteAuthorityValidator

__all__ = [
    "FederationValidationError",
    "FilesystemRecorderStorageProvider",
    "FilesystemBatchStorageProvider",
    "PostgreSQLBatchStorageProvider",
    "BatchStorageProvider",
    "LocalStorageService",
    "AuthorizedStorageService",
    "StorageWriteAuthorityValidator",
    "LogicalStorageClient",
    "StorageRoute",
    "StorageRouteResolver",
    "StorageRequestTransport",
    "CallableStorageTransport",
    "RelayNodeStorageTransport",
    "SQLiteOutbox",
    "OutboxEntry",
    "OutboxState",
    "StorageProvider",
    "CapabilityProvider",
    "ProviderError",
    "ProviderErrorCode",
    "StorageReadOutcome",
    "StorageWriteOutcome",
    "LocalCapabilityRegistry",
    "CapabilityAnnouncement",
    "CapabilityStatus",
    "CommitState",
    "DatasetCoverage",
    "LeadershipGrant",
    "LeaderSelectionResult",
    "NodeIdentity",
    "Session",
    "SessionEvent",
    "SessionState",
    "StorageBatch",
    "StorageGroupState",
    "StorageGroupPolicy",
    "StorageManifest",
    "StorageNodeState",
    "StorageRole",
    "StorageWriteRequest",
    "select_storage_leader",
    "validate_primary_write",
    "STORAGE_GROUP_CREATED",
    "STORAGE_PROVIDER_REGISTERED",
    "STORAGE_PROVIDER_REMOVED",
    "STORAGE_ASSIGNMENT_CHANGED",
    "STORAGE_LEADER_GRANTED",
    "STORAGE_LEADER_REVOKED",
    "StorageProviderRegistration",
    "StorageGroupAssignment",
    "StorageControlPlaneSnapshot",
    "StorageControlPlaneStore",
    "STORAGE_PROTOCOL",
    "STORAGE_PROTOCOL_MAJOR",
    "STORAGE_PROTOCOL_VERSION",
    "BatchIngestRequest",
    "BatchIngestResult",
    "BatchIngestState",
    "StorageError",
    "StorageErrorCode",
    "StorageOperation",
    "StorageRequestEnvelope",
    "StorageResponseEnvelope",
    "WriteAuthority",
    "classify_idempotent_ingest",
    "validate_protocol_version",
]